In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plb

In [4]:
import seaborn as sns

In [14]:
df = pd.read_csv(r"C:\Users\USER\Desktop\ML_PROJECTS\AmesHousing.csv")

In [15]:
df.head(10)

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900
5,6,527105030,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,195500
6,7,527127150,120,RL,41.0,4920,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,213500
7,8,527145080,120,RL,43.0,5005,Pave,NaN,IR1,HLS,...,0,NaN,NaN,NaN,0,1,2010,WD,Normal,191500
8,9,527146030,120,RL,39.0,5389,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,3,2010,WD,Normal,236500
9,10,527162130,60,RL,60.0,7500,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,189000

In [16]:
pd.set_option('display.max_columns', None)

In [17]:
df.head(10)

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,5,1960,1960,Hip,CompShg,BrkFace,Plywood,Stone,112.0,TA,TA,CBlock,TA,Gd,Gd,BLQ,639.0,Unf,0.0,441.0,1080.0,GasA,Fa,Y,SBrkr,1656,0,0,1656,1.0,0.0,1,0,3,1,TA,7,Typ,2,Gd,Attchd,1960.0,Fin,2.0,528.0,TA,TA,P,210,62,0,0,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,Norm,1Fam,1Story,5,6,1961,1961,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,CBlock,TA,TA,No,Rec,468.0,LwQ,144.0,270.0,882.0,GasA,TA,Y,SBrkr,896,0,0,896,0.0,0.0,1,0,2,1,TA,5,Typ,0,NaN,Attchd,1961.0,Unf,1.0,730.0,TA,TA,Y,140,0,0,0,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,6,1958,1958,Hip,CompShg,Wd Sdng,Wd Sdng,BrkFace,108.0,TA,TA,CBlock,TA,TA,No,ALQ,923.0,Unf,0.0,406.0,1329.0,GasA,TA,Y,SBrkr,1329,0,0,1329,0.0,0.0,1,1,3,1,Gd,6,Typ,0,NaN,Attchd,1958.0,Unf,1.0,312.0,TA,TA,Y,393,36,0,0,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,7,5,1968,1968,Hip,CompShg,BrkFace,BrkFace,NaN,0.0,Gd,TA,CBlock,TA,TA,No,ALQ,1065.0,Unf,0.0,1045.0,2110.0,GasA,Ex,Y,SBrkr,2110,0,0,2110,1.0,0.0,2,1,3,1,Ex,8,Typ,2,TA,Attchd,1968.0,Fin,2.0,522.0,TA,TA,Y,0,0,0,0,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,5,5,1997,1998,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,PConc,Gd,TA,No,GLQ,791.0,Unf,0.0,137.0,928.0,GasA,Gd,Y,SBrkr,928,701,0,1629,0.0,0.0,2,1,3,1,TA,6,Typ,1,TA,Attchd,1997.0,Fin,2.0,482.0,TA,TA,Y,212,34,0,0,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900
5,6,527105030,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,6,1998,1998,Gable,CompShg,VinylSd,VinylSd,BrkFace,20.0,TA,TA,PConc,TA,TA,No,GLQ,602.0,Unf,0.0,324.0,926.0,GasA,Ex,Y,SBrkr,926,678,0,1604,0.0,0.0,2,1,3,1,Gd,7,Typ,1,Gd,Attchd,1998.0,Fin,2.0,470.0,TA,TA,Y,360,36,0,0,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal,195500
6,7,527127150,120,RL,41.0,4920,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,StoneBr,Norm,Norm,TwnhsE,1Story,8,5,2001,2001,Gable,CompShg,CemntBd,CmentBd,NaN,0.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,616.0,Unf,0.0,722.0,1338.0,GasA,Ex,Y,SBrkr,1338,0,0,1338,1.0,0.0,2,0,2,1,Gd,6,Typ,0,NaN,Attchd,2001.0,Fin,2.0,582.0,TA,TA,Y,0,0,170,0,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal,213500
7,8,527145080,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,Inside,Gtl,StoneBr,Norm,Norm,TwnhsE,1Story,8,5,1992,1992,Gable,CompShg,HdBoard,HdBoard,NaN,0.0,Gd,TA,PConc,Gd,TA,No,ALQ,263.0,Unf,0.0,1017.0,1280.0,GasA,Ex,Y,SBrkr,1280,0,0,1280,0.0,0.0,2,0,2,1,Gd,5,Typ,0,NaN,Attchd,1992.0,RFn,2.0,506.0,TA,TA,Y,0,82,0,0,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal,191500
8,9,527146030,120,RL,39.0,5389,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,StoneBr,Norm,Norm,TwnhsE,1Story,8,5,1995,1996,Gable,CompShg,CemntBd,CmentBd,NaN,0.0,Gd,TA,PConc,Gd,TA,No,GLQ,1180.0,Unf,0.0,415.0,1595.0,GasA,Ex,Y,SBrkr,1616,0,0,1616,1.0,0.0,2,0,2,1,Gd,5,Typ,1,TA,Attchd,1995.0,RFn,2.0,608.0,TA,TA,Y,237,152,0,0,0,0,NaN,NaN,NaN,0,3,2010,WD,Normal,236500
9,10,527162130,60,RL,60.0,7500,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,7,5,1999,1999,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,PConc,TA,TA,No,Unf,0.0,Unf,0.0,994.0,994.0,GasA,Gd,Y,SBrkr,1028,776,0,1804,0.0,0.0,2,1,3,1,Gd,7,Typ,1,TA,Attchd,1999.0,Fin,2.0,442.0,TA,TA,Y,140,60,0,0,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal,189000

In [18]:
df.tail(10)

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
2920,2921,923228310,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,MeadowV,Norm,Norm,TwnhsE,2Story,4,5,1970,1970,Gable,CompShg,CemntBd,CmentBd,NaN,0.0,TA,TA,CBlock,TA,TA,No,Rec,252.0,Unf,0.0,294.0,546.0,GasA,TA,Y,SBrkr,546,546,0,1092,0.0,0.0,1,1,3,1,TA,6,Typ,0,NaN,CarPort,1970.0,Unf,1.0,286.0,TA,TA,Y,0,24,0,0,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,71000
2921,2922,923229110,90,RL,55.0,12640,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Mitchel,Norm,Norm,Duplex,1Story,6,5,1976,1976,Gable,CompShg,Plywood,Plywood,NaN,0.0,TA,TA,CBlock,TA,TA,Gd,Rec,936.0,LwQ,396.0,396.0,1728.0,GasA,TA,Y,SBrkr,1728,0,0,1728,0.0,0.0,2,0,4,2,TA,8,Typ,0,NaN,Attchd,1976.0,Unf,2.0,574.0,TA,TA,Y,40,0,0,0,0,0,NaN,NaN,NaN,0,7,2006,WD,Normal,150900
2922,2923,923230040,90,RL,63.0,9297,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Mitchel,Norm,Norm,Duplex,1Story,5,5,1976,1976,Gable,CompShg,Plywood,Plywood,NaN,0.0,TA,TA,CBlock,TA,TA,No,ALQ,1606.0,Unf,0.0,122.0,1728.0,GasA,TA,Y,SBrkr,1728,0,0,1728,2.0,0.0,2,0,4,2,TA,8,Typ,0,NaN,Detchd,1976.0,Unf,2.0,560.0,TA,TA,Y,0,0,0,0,0,0,NaN,NaN,NaN,0,7,2006,WD,Family,188000
2923,2924,923250060,20,RL,80.0,17400,Pave,NaN,Reg,Low,AllPub,Inside,Mod,Mitchel,Norm,Norm,1Fam,1Story,5,5,1977,1977,Gable,CompShg,BrkFace,BrkFace,NaN,0.0,TA,TA,CBlock,TA,TA,No,ALQ,936.0,Unf,0.0,190.0,1126.0,GasA,Fa,Y,SBrkr,1126,0,0,1126,1.0,0.0,2,0,3,1,TA,5,Typ,1,Gd,Attchd,1977.0,RFn,2.0,484.0,TA,TA,P,295,41,0,0,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal,160000
2924,2925,923251180,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Mitchel,Norm,Norm,1Fam,1Story,5,7,1960,1996,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,CBlock,TA,TA,No,ALQ,1224.0,Unf,0.0,0.0,1224.0,GasA,Ex,Y,SBrkr,1224,0,0,1224,1.0,0.0,1,0,4,1,TA,7,Typ,1,TA,Detchd,1960.0,Unf,2.0,576.0,TA,TA,Y,474,0,0,0,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml,131000
2925,2926,923275080,80,RL,37.0,7937,Pave,NaN,IR1,Lvl,AllPub,CulDSac,Gtl,Mitchel,Norm,Norm,1Fam,SLvl,6,6,1984,1984,Gable,CompShg,HdBoard,HdBoard,NaN,0.0,TA,TA,CBlock,TA,TA,Av,GLQ,819.0,Unf,0.0,184.0,1003.0,GasA,TA,Y,SBrkr,1003,0,0,1003,1.0,0.0,1,0,3,1,TA,6,Typ,0,NaN,Detchd,1984.0,Unf,2.0,588.0,TA,TA,Y,120,0,0,0,0,0,NaN,GdPrv,NaN,0,3,2006,WD,Normal,142500
2926,2927,923276100,20,RL,NaN,8885,Pave,NaN,IR1,Low,AllPub,Inside,Mod,Mitchel,Norm,Norm,1Fam,1Story,5,5,1983,1983,Gable,CompShg,HdBoard,HdBoard,NaN,0.0,TA,TA,CBlock,Gd,TA,Av,BLQ,301.0,ALQ,324.0,239.0,864.0,GasA,TA,Y,SBrkr,902,0,0,902,1.0,0.0,1,0,2,1,TA,5,Typ,0,NaN,Attchd,1983.0,Unf,2.0,484.0,TA,TA,Y,164,0,0,0,0,0,NaN,MnPrv,NaN,0,6,2006,WD,Normal,131000
2927,2928,923400125,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Mitchel,Norm,Norm,1Fam,SFoyer,5,5,1992,1992,Gable,CompShg,HdBoard,Wd Shng,NaN,0.0,TA,TA,PConc,Gd,TA,Av,GLQ,337.0,Unf,0.0,575.0,912.0,GasA,TA,Y,SBrkr,970,0,0,970,0.0,1.0,1,0,3,1,TA,6,Typ,0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Y,80,32,0,0,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,132000
2928,2929,924100070,20,RL,77.0,10010,Pave,NaN,Reg,Lvl,AllPub,Inside,Mod,Mitchel,Norm,Norm,1Fam,1Story,5,5,1974,1975,Gable,CompShg,HdBoard,HdBoard,NaN,0.0,TA,TA,CBlock,Gd,TA,Av,ALQ,1071.0,LwQ,123.0,195.0,1389.0,GasA,Gd,Y,SBrkr,1389,0,0,1389,1.0,0.0,1,0,2,1,TA,6,Typ,1,TA,Attchd,1975.0,RFn,2.0,418.0,TA,TA,Y,240,38,0,0,0,0,NaN,NaN,NaN,0,4,2006,WD,Normal,170000
2929,2930,924151050,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,Inside,Mod,Mitchel,Norm,Norm,1Fam,2Story,7,5,1993,1994,Gable,CompShg,HdBoard,HdBoard,BrkFace,94.0,TA,TA,PConc,Gd,TA,Av,LwQ,758.0,Unf,0.0,238.0,996.0,GasA,Ex,Y,SBrkr,996,1004,0,2000,0.0,0.0,2,1,3,1,TA,9,Typ,1,TA,Attchd,1993.0,Fin,3.0,650.0,TA,TA,Y,190,48,0,0,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal,188000

In [19]:
df.shape

(2930, 82)

In [20]:
df.columns

Index(['Order', 'PID', 'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area',
       'Street', 'Alley', 'Lot Shape', 'Land Contour', 'Utilities',
       'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1',
       'Condition 2', 'Bldg Type', 'House Style', 'Overall Qual',
       'Overall Cond', 'Year Built', 'Year Remod/Add', 'Roof Style',
       'Roof Matl', 'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type',
       'Mas Vnr Area', 'Exter Qual', 'Exter Cond', 'Foundation', 'Bsmt Qual',
       'Bsmt Cond', 'Bsmt Exposure', 'BsmtFin Type 1', 'BsmtFin SF 1',
       'BsmtFin Type 2', 'BsmtFin SF 2', 'Bsmt Unf SF', 'Total Bsmt SF',
       'Heating', 'Heating QC', 'Central Air', 'Electrical', '1st Flr SF',
       '2nd Flr SF', 'Low Qual Fin SF', 'Gr Liv Area', 'Bsmt Full Bath',
       'Bsmt Half Bath', 'Full Bath', 'Half Bath', 'Bedroom AbvGr',
       'Kitchen AbvGr', 'Kitchen Qual', 'TotRms AbvGrd', 'Functional',
       'Fireplaces', 'Fireplace Qu', 'Garage Type', 'Garage Yr Blt',
       'Garage Finish', 'Garage Cars', 'Garage Area', 'Garage Qual',
       'Garage Cond', 'Paved Drive', 'Wood Deck SF', 'Open Porch SF',
       'Enclosed Porch', '3Ssn Porch', 'Screen Porch', 'Pool Area', 'Pool QC',
       'Fence', 'Misc Feature', 'Misc Val', 'Mo Sold', 'Yr Sold', 'Sale Type',
       'Sale Condition', 'SalePrice'],
      dtype='object')

In [21]:
df.dtypes

Order               int64
PID                 int64
MS SubClass         int64
MS Zoning          object
Lot Frontage      float64
                   ...
Mo Sold             int64
Yr Sold             int64
Sale Type          object
Sale Condition     object
SalePrice           int64
Length: 82, dtype: object

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   int64
 1   PID              2930 non-null   int64
 2   MS SubClass      2930 non-null   int64
 3   MS Zoning        2930 non-null   object
 4   Lot Frontage     2440 non-null   float64
 5   Lot Area         2930 non-null   int64
 6   Street           2930 non-null   object
 7   Alley            198 non-null    object
 8   Lot Shape        2930 non-null   object
 9   Land Contour     2930 non-null   object
 10  Utilities        2930 non-null   object
 11  Lot Config       2930 non-null   object
 12  Land Slope       2930 non-null   object
 13  Neighborhood     2930 non-null   object
 14  Condition 1      2930 non-null   object
 15  Condition 2      2930 non-null   object
 16  Bldg Type        2930 non-null   object
 17  House Style      2930 non-null   object
 18  Overall Qual     2930 non-null   int64
 19  Overall Cond     2930 non-null   int64
 20  Year Built       2930 non-null   int64
 21  Year Remod/Add   2930 non-null   int64
 22  Roof Style       2930 non-null   object
 23  Roof Matl        2930 non-null   object
 24  Exterior 1st     2930 non-null   object
 25  Exterior 2nd     2930 non-null   object
 26  Mas Vnr Type     1155 non-null   object
 27  Mas Vnr Area     2907 non-null   float64
 28  Exter Qual       2930 non-null   object
 29  Exter Cond       2930 non-null   object
 30  Foundation       2930 non-null   object
 31  Bsmt Qual        2850 non-null   object
 32  Bsmt Cond        2850 non-null   object
 33  Bsmt Exposure    2847 non-null   object
 34  BsmtFin Type 1   2850 non-null   object
 35  BsmtFin SF 1     2929 non-null   float64
 36  BsmtFin Type 2   2849 non-null   object
 37  BsmtFin SF 2     2929 non-null   float64
 38  Bsmt Unf SF      2929 non-null   float64
 39  Total Bsmt SF    2929 non-null   float64
 40  Heating          2930 non-null   object
 41  Heating QC       2930 non-null   object
 42  Central Air      2930 non-null   object
 43  Electrical       2929 non-null   object
 44  1st Flr SF       2930 non-null   int64
 45  2nd Flr SF       2930 non-null   int64
 46  Low Qual Fin SF  2930 non-null   int64
 47  Gr Liv Area      2930 non-null   int64
 48  Bsmt Full Bath   2928 non-null   float64
 49  Bsmt Half Bath   2928 non-null   float64
 50  Full Bath        2930 non-null   int64
 51  Half Bath        2930 non-null   int64
 52  Bedroom AbvGr    2930 non-null   int64
 53  Kitchen AbvGr    2930 non-null   int64
 54  Kitchen Qual     2930 non-null   object
 55  TotRms AbvGrd    2930 non-null   int64
 56  Functional       2930 non-null   object
 57  Fireplaces       2930 non-null   int64
 58  Fireplace Qu     1508 non-null   object
 59  Garage Type      2773 non-null   object
 60  Garage Yr Blt    2771 non-null   float64
 61  Garage Finish    2771 non-null   object
 62  Garage Cars      2929 non-null   float64
 63  Garage Area      2929 non-null   float64
 64  Garage Qual      2771 non-null   object
 65  Garage Cond      2771 non-null   object
 66  Paved Drive      2930 non-null   object
 67  Wood Deck SF     2930 non-null   int64
 68  Open Porch SF    2930 non-null   int64
 69  Enclosed Porch   2930 non-null   int64
 70  3Ssn Porch       2930 non-null   int64
 71  Screen Porch     2930 non-null   int64
 72  Pool Area        2930 non-null   int64
 73  Pool QC          13 non-null     object
 74  Fence            572 non-null    object
 75  Misc Feature     106 non-null    object
 76  Misc Val         2930 non-null   int64
 77  Mo Sold          2930 non-null   int64
 78  Yr Sold          2930 non-null   int64
 79  Sale Type        2930 non-null   object
 80  Sale Condition   2930 non-null   object
 81  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(28), object(43)
memory usage: 1.8+ MB

In [23]:
df.describe()

,Order,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,TotRms AbvGrd,Fireplaces,Garage Yr Blt,Garage Cars,Garage Area,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
count,2930.00000,2.930000e+03,2930.000000,2440.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2907.000000,2929.000000,2929.000000,2929.000000,2929.000000,2930.000000,2930.000000,2930.000000,2930.000000,2928.000000,2928.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2771.000000,2929.000000,2929.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000
mean,1465.50000,7.144645e+08,57.387372,69.224590,10147.921843,6.094881,5.563140,1971.356314,1984.266553,101.896801,442.629566,49.722431,559.262547,1051.614544,1159.557679,335.455973,4.676792,1499.690444,0.431352,0.061134,1.566553,0.379522,2.854266,1.044369,6.443003,0.599317,1978.132443,1.766815,472.819734,93.751877,47.533447,23.011604,2.592491,16.002048,2.243345,50.635154,6.216041,2007.790444,180796.060068
std,845.96247,1.887308e+08,42.638025,23.365335,7880.017759,1.411026,1.111537,30.245361,20.860286,179.112611,455.590839,169.168476,439.494153,440.615067,391.890885,428.395715,46.310510,505.508887,0.524820,0.245254,0.552941,0.502629,0.827731,0.214076,1.572964,0.647921,25.528411,0.760566,215.046549,126.361562,67.483400,64.139059,25.141331,56.087370,35.597181,566.344288,2.714492,1.316613,79886.692357
min,1.00000,5.263011e+08,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,0.000000,0.000000,334.000000,0.000000,0.000000,334.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,1895.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,12789.000000
25%,733.25000,5.284770e+08,20.000000,58.000000,7440.250000,5.000000,5.000000,1954.000000,1965.000000,0.000000,0.000000,0.000000,219.000000,793.000000,876.250000,0.000000,0.000000,1126.000000,0.000000,0.000000,1.000000,0.000000,2.000000,1.000000,5.000000,0.000000,1960.000000,1.000000,320.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129500.000000
50%,1465.50000,5.354536e+08,50.000000,68.000000,9436.500000,6.000000,5.000000,1973.000000,1993.000000,0.000000,370.000000,0.000000,466.000000,990.000000,1084.000000,0.000000,0.000000,1442.000000,0.000000,0.000000,2.000000,0.000000,3.000000,1.000000,6.000000,1.000000,1979.000000,2.000000,480.000000,0.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,160000.000000
75%,2197.75000,9.071811e+08,70.000000,80.000000,11555.250000,7.000000,6.000000,2001.000000,2004.000000,164.000000,734.000000,0.000000,802.000000,1302.000000,1384.000000,703.750000,0.000000,1742.750000,1.000000,0.000000,2.000000,1.000000,3.000000,1.000000,7.000000,1.000000,2002.000000,2.000000,576.000000,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,213500.000000
max,2930.00000,1.007100e+09,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,1526.000000,2336.000000,6110.000000,5095.000000,2065.000000,1064.000000,5642.000000,3.000000,2.000000,4.000000,2.000000,8.000000,3.000000,15.000000,4.000000,2207.000000,5.000000,1488.000000,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000

In [24]:
df.columns = df.columns.str.strip()

In [25]:
#TO REMOVE LEADING/TRAILING SPACES FROM COLUMN NAMES#

In [26]:
df.columns

Index(['Order', 'PID', 'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area',
       'Street', 'Alley', 'Lot Shape', 'Land Contour', 'Utilities',
       'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1',
       'Condition 2', 'Bldg Type', 'House Style', 'Overall Qual',
       'Overall Cond', 'Year Built', 'Year Remod/Add', 'Roof Style',
       'Roof Matl', 'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type',
       'Mas Vnr Area', 'Exter Qual', 'Exter Cond', 'Foundation', 'Bsmt Qual',
       'Bsmt Cond', 'Bsmt Exposure', 'BsmtFin Type 1', 'BsmtFin SF 1',
       'BsmtFin Type 2', 'BsmtFin SF 2', 'Bsmt Unf SF', 'Total Bsmt SF',
       'Heating', 'Heating QC', 'Central Air', 'Electrical', '1st Flr SF',
       '2nd Flr SF', 'Low Qual Fin SF', 'Gr Liv Area', 'Bsmt Full Bath',
       'Bsmt Half Bath', 'Full Bath', 'Half Bath', 'Bedroom AbvGr',
       'Kitchen AbvGr', 'Kitchen Qual', 'TotRms AbvGrd', 'Functional',
       'Fireplaces', 'Fireplace Qu', 'Garage Type', 'Garage Yr Blt',
       'Garage Finish', 'Garage Cars', 'Garage Area', 'Garage Qual',
       'Garage Cond', 'Paved Drive', 'Wood Deck SF', 'Open Porch SF',
       'Enclosed Porch', '3Ssn Porch', 'Screen Porch', 'Pool Area', 'Pool QC',
       'Fence', 'Misc Feature', 'Misc Val', 'Mo Sold', 'Yr Sold', 'Sale Type',
       'Sale Condition', 'SalePrice'],
      dtype='object')

In [27]:
#TO CHECK THE COLUMN NAMES AGAIN AND ENSURE THE SPACES ARE REMOVED#

In [28]:
df.isnull().sum()

Order               0
PID                 0
MS SubClass         0
MS Zoning           0
Lot Frontage      490
                 ...
Mo Sold             0
Yr Sold             0
Sale Type           0
Sale Condition      0
SalePrice           0
Length: 82, dtype: int64

In [29]:
#TO CHECK HOW MANY MISSING VALUES EACH COLUMN HAVE...BUT THIS DOESN'T DISPLAY ALL IN A BETTER WAY FOR A LARGER DATASET LIKE#

In [30]:
missing = df.isnull().sum()
missing[missing>0]

Lot Frontage       490
Alley             2732
Mas Vnr Type      1775
Mas Vnr Area        23
Bsmt Qual           80
Bsmt Cond           80
Bsmt Exposure       83
BsmtFin Type 1      80
BsmtFin SF 1         1
BsmtFin Type 2      81
BsmtFin SF 2         1
Bsmt Unf SF          1
Total Bsmt SF        1
Electrical           1
Bsmt Full Bath       2
Bsmt Half Bath       2
Fireplace Qu      1422
Garage Type        157
Garage Yr Blt      159
Garage Finish      159
Garage Cars          1
Garage Area          1
Garage Qual        159
Garage Cond        159
Pool QC           2917
Fence             2358
Misc Feature      2824
dtype: int64

In [31]:
#THIS CODES SHOWS THE COLUMNS THAT ACTUALY HAVE MISSING VALUES. THEREFORE, THIS CODE IS BETTER THAN THE FORMER#

In [32]:
missing = df.isnull().sum()
missing_percent = (missing/len(df)) * 100
missing_data = pd.DataFrame({'Missing Values': missing, 'Percentage': missing_percent
                            })
missing_data[missing_data['Missing Values']>0].sort_values(by='Percentage',
                                                          ascending=False
                                                         )

                Missing Values  Percentage
Pool QC                   2917   99.556314
Misc Feature              2824   96.382253
Alley                     2732   93.242321
Fence                     2358   80.477816
Mas Vnr Type              1775   60.580205
Fireplace Qu              1422   48.532423
Lot Frontage               490   16.723549
Garage Cond                159    5.426621
Garage Qual                159    5.426621
Garage Finish              159    5.426621
Garage Yr Blt              159    5.426621
Garage Type                157    5.358362
Bsmt Exposure               83    2.832765
BsmtFin Type 2              81    2.764505
Bsmt Cond                   80    2.730375
Bsmt Qual                   80    2.730375
BsmtFin Type 1              80    2.730375
Mas Vnr Area                23    0.784983
Bsmt Half Bath               2    0.068259
Bsmt Full Bath               2    0.068259
BsmtFin SF 1                 1    0.034130
Garage Cars                  1    0.034130
Garage Area                  1    0.034130
Total Bsmt SF                1    0.034130
Bsmt Unf SF                  1    0.034130
BsmtFin SF 2                 1    0.034130
Electrical                   1    0.034130

In [33]:
#TO SEE THE MISSING VALUES AND THEIR PERCENTAGES#

In [34]:
#WE MAY NT DROP DOZ HIGH-MISSING CATEGORICAL COLUMNS EVEN THOUGH THEY'RE MISSING BUT RATHER ASSUME THEY DNN'T EXIST & OTHERS#

In [35]:
none_cols = [
    'Pool QC', 
    'Misc Feature',
    'Alley',
    'Fence',
    'Mas Vnr Type',
    'Fireplace Qu',
    'Garage Cond', 
    'Garage Qual',
    'Garage Finish',
    'Garage Yr Blt',
    'Garage Type',
    'Bsmt Exposure',
    'Bsmt Qual',
     'Bsmt Cond',
     'BsmtFin Type 1',
    'BsmtFin Type 2'
    ]

df[none_cols] = df[none_cols].fillna('None')

In [36]:
df[none_cols].isnull().sum()

Pool QC           0
Misc Feature      0
Alley             0
Fence             0
Mas Vnr Type      0
Fireplace Qu      0
Garage Cond       0
Garage Qual       0
Garage Finish     0
Garage Yr Blt     0
Garage Type       0
Bsmt Exposure     0
Bsmt Qual         0
Bsmt Cond         0
BsmtFin Type 1    0
BsmtFin Type 2    0
dtype: int64

In [37]:
#CHECK MISSING VALUES IN THOSE SPECIFIC COLUMNS

In [38]:
missing = df.isnull().sum()

missing_data = pd.DataFrame({
    'Missing Values': missing,
    'Percentage': (missing / len(df)) * 100
})

missing_data[missing_data['Missing Values'] > 0].sort_values(
    by='Percentage',
    ascending=False
)

                Missing Values  Percentage
Lot Frontage               490   16.723549
Mas Vnr Area                23    0.784983
Bsmt Full Bath               2    0.068259
Bsmt Half Bath               2    0.068259
BsmtFin SF 1                 1    0.034130
BsmtFin SF 2                 1    0.034130
Bsmt Unf SF                  1    0.034130
Total Bsmt SF                1    0.034130
Electrical                   1    0.034130
Garage Cars                  1    0.034130
Garage Area                  1    0.034130

In [39]:
df['Lot Frontage'] = df['Lot Frontage'].fillna(
    df['Lot Frontage'].median()
)

In [40]:
df['Lot Frontage'].isnull().sum()

np.int64(0)

In [41]:
df['Mas Vnr Area'] = df['Mas Vnr Area'].fillna(0)

In [42]:
df['Mas Vnr Area'].isnull().sum()

np.int64(0)

In [43]:
bsmt_num_cols = [
    'Bsmt Full Bath',
    'Bsmt Half Bath',
    'BsmtFin SF 1',
    'BsmtFin SF 2',
    'Bsmt Unf SF',
    'Total Bsmt SF'
]

df[bsmt_num_cols] = df[bsmt_num_cols].fillna(0)

In [44]:
garage_num_cols = [
    'Garage Cars',
    'Garage Area'
]

df[garage_num_cols] = df[garage_num_cols].fillna(0)

In [45]:
df['Electrical'] = df['Electrical'].fillna(
    df['Electrical'].mode()[0]
)

In [46]:
missing = df.isnull().sum()

missing_data = pd.DataFrame({
    'Missing Values': missing,
    'Percentage': (missing / len(df)) * 100
})

missing_data[missing_data['Missing Values'] > 0].sort_values(
    by='Percentage',
    ascending=False
)

Empty DataFrame
Columns: [Missing Values, Percentage]
Index: []

In [47]:
# Check total number of missing values in the entire dataset
df.isnull().sum().sum()

np.int64(0)

In [48]:
#CHECK FOR DUPLICATE ROWS#
df.duplicated().sum()

np.int64(0)

In [49]:
#Check for impossible or suspicious values#
(df["SalePrice"] <= 0).sum()

np.int64(0)

In [50]:
#Check categorical variables#
df.select_dtypes(include="object").columns

Index(['MS Zoning', 'Street', 'Alley', 'Lot Shape', 'Land Contour',
       'Utilities', 'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1',
       'Condition 2', 'Bldg Type', 'House Style', 'Roof Style', 'Roof Matl',
       'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type', 'Exter Qual',
       'Exter Cond', 'Foundation', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure',
       'BsmtFin Type 1', 'BsmtFin Type 2', 'Heating', 'Heating QC',
       'Central Air', 'Electrical', 'Kitchen Qual', 'Functional',
       'Fireplace Qu', 'Garage Type', 'Garage Yr Blt', 'Garage Finish',
       'Garage Qual', 'Garage Cond', 'Paved Drive', 'Pool QC', 'Fence',
       'Misc Feature', 'Sale Type', 'Sale Condition'],
      dtype='object')

In [51]:
#CHECK FOR OUTLIERS#
df["SalePrice"].describe()

count      2930.000000
mean     180796.060068
std       79886.692357
min       12789.000000
25%      129500.000000
50%      160000.000000
75%      213500.000000
max      755000.000000
Name: SalePrice, dtype: float64

In [52]:
#CHECK FOR OUTLIERS#
Q1 = df["SalePrice"].quantile(0.25)
Q3 = df["SalePrice"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

Q1: 129500.0
Q3: 213500.0
IQR: 84000.0
Lower bound: 3500.0
Upper bound: 339500.0

In [53]:
#FIND HOW MANY POTENTIAL OUTLIERS ARE THERE#
outliers = df[
    (df["SalePrice"] < lower_bound) |
    (df["SalePrice"] > upper_bound)
]

print("Number of potential outliers:", len(outliers))

Number of potential outliers: 137

In [54]:
#HOUSES ASSOCIATED WITH THOSE OUTLIERS#
print(
    outliers[
        ["SalePrice", "Overall Qual", "Gr Liv Area", "Year Built", "Garage Cars", "Garage Area"]
    ].sort_values("SalePrice", ascending=False)
)

      SalePrice  Overall Qual  Gr Liv Area  Year Built  Garage Cars  \
1767     755000            10         4316        1994          3.0
1760     745000            10         4476        1996          3.0
2445     625000            10         3627        1995          3.0
1063     615000            10         2470        2003          3.0
44       611657             9         2364        2009          3.0
...         ...           ...          ...         ...          ...
1707     342000             8         2956        2004          3.0
1106     341000             7         2418        1993          3.0
497      340000             8         2450        1998          3.0
1805     340000             8         2466        2004          2.0
1126     339750             8         2078        2007          3.0

      Garage Area
1767        832.0
1760        813.0
2445        807.0
1063        789.0
44          820.0
...           ...
1707        916.0
1106        983.0
497        1069.0
1805        610.0
1126        836.0

[137 rows x 6 columns]

In [55]:
#Check the distribution of your major variables#
import matplotlib.pyplot as plt

for col in important_cols:
    plt.figure(figsize=(7, 4))
    plt.boxplot(df[col].dropna())
    plt.title(f"{col} - Boxplot")
    plt.ylabel(col)
    plt.show()

NameError: name 'important_cols' is not defined

In [ ]:
important_cols = [
    "Lot Area",
    "Overall Qual",
    "Year Built",
    "Year Remod/Add",
    "Total Bsmt SF",
    "1st Flr SF",
    "2nd Flr SF",
    "Gr Liv Area",
    "Garage Cars",
    "Garage Area",
    "SalePrice"
]

In [57]:
#INSPECT THE 137 OUTLIERS#
upper_bound = 339500

In [58]:
outliers = df[df["SalePrice"] > 339500]

In [59]:
outliers[
    [
        "SalePrice",
        "Overall Qual",
        "Gr Liv Area",
        "Year Built",
        "Garage Cars",
        "Garage Area",
        "Overall Cond"
    ]
].sort_values("SalePrice", ascending=False)

,SalePrice,Overall Qual,Gr Liv Area,Year Built,Garage Cars,Garage Area,Overall Cond
1767,755000,10,4316,1994,3.0,832.0,6
1760,745000,10,4476,1996,3.0,813.0,5
2445,625000,10,3627,1995,3.0,807.0,5
1063,615000,10,2470,2003,3.0,789.0,5
44,611657,9,2364,2009,3.0,820.0,5
...,...,...,...,...,...,...,...
1707,342000,8,2956,2004,3.0,916.0,5
1106,341000,7,2418,1993,3.0,983.0,5
497,340000,8,2450,1998,3.0,1069.0,5
1805,340000,8,2466,2004,2.0,610.0,5
1126,339750,8,2078,2007,3.0,836.0,5

In [60]:
df.isnull().sum().sum()

np.int64(0)

In [61]:
df.isnull().sum().sort_values(ascending=False)

Order            0
Garage Finish    0
Garage Type      0
Fireplace Qu     0
Fireplaces       0
                ..
Mas Vnr Type     0
Exterior 2nd     0
Exterior 1st     0
Roof Matl        0
SalePrice        0
Length: 82, dtype: int64

In [62]:
missing = df.isnull().sum()

missing = missing[missing > 0].sort_values(ascending=False)

print(missing)

Series([], dtype: int64)

In [63]:
print(df.shape)

(2930, 82)

In [64]:
df["Mas Vnr Area"] = df["Mas Vnr Area"].fillna(0)

df["Garage Yr Blt"] = df["Garage Yr Blt"].fillna(0)

In [65]:
df["Lot Frontage"] = df["Lot Frontage"].fillna(
    df["Lot Frontage"].median()
)

In [66]:
bsmt_num_cols = [
    "Bsmt Half Bath",
    "Bsmt Full Bath",
    "BsmtFin SF 1",
    "BsmtFin SF 2",
    "Total Bsmt SF",
    "Bsmt Unf SF"
]

df[bsmt_num_cols] = df[bsmt_num_cols].fillna(0)

In [67]:
garage_num_cols = [
    "Garage Cars",
    "Garage Area"
]

df[garage_num_cols] = df[garage_num_cols].fillna(0)

In [68]:
df["Electrical"] = df["Electrical"].fillna(
    df["Electrical"].mode()[0]
)

In [69]:
df.isnull().sum().sort_values(ascending=False)

Order            0
Garage Finish    0
Garage Type      0
Fireplace Qu     0
Fireplaces       0
                ..
Mas Vnr Type     0
Exterior 2nd     0
Exterior 1st     0
Roof Matl        0
SalePrice        0
Length: 82, dtype: int64

In [70]:
print("Total missing values:", df.isnull().sum().sum())

Total missing values: 0

In [71]:
missing = df.isnull().sum()

missing = missing[missing > 0].sort_values(ascending=False)

print(missing)

Series([], dtype: int64)

In [72]:
print(df.columns.tolist())

['Order', 'PID', 'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area', 'Street', 'Alley', 'Lot Shape', 'Land Contour', 'Utilities', 'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1', 'Condition 2', 'Bldg Type', 'House Style', 'Overall Qual', 'Overall Cond', 'Year Built', 'Year Remod/Add', 'Roof Style', 'Roof Matl', 'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type', 'Mas Vnr Area', 'Exter Qual', 'Exter Cond', 'Foundation', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure', 'BsmtFin Type 1', 'BsmtFin SF 1', 'BsmtFin Type 2', 'BsmtFin SF 2', 'Bsmt Unf SF', 'Total Bsmt SF', 'Heating', 'Heating QC', 'Central Air', 'Electrical', '1st Flr SF', '2nd Flr SF', 'Low Qual Fin SF', 'Gr Liv Area', 'Bsmt Full Bath', 'Bsmt Half Bath', 'Full Bath', 'Half Bath', 'Bedroom AbvGr', 'Kitchen AbvGr', 'Kitchen Qual', 'TotRms AbvGrd', 'Functional', 'Fireplaces', 'Fireplace Qu', 'Garage Type', 'Garage Yr Blt', 'Garage Finish', 'Garage Cars', 'Garage Area', 'Garage Qual', 'Garage Cond', 'Paved Drive', 'Wood Deck SF', 'Open Porch SF', 'Enclosed Porch', '3Ssn Porch', 'Screen Porch', 'Pool Area', 'Pool QC', 'Fence', 'Misc Feature', 'Misc Val', 'Mo Sold', 'Yr Sold', 'Sale Type', 'Sale Condition', 'SalePrice']

In [73]:
print(df.dtypes)

Order               int64
PID                 int64
MS SubClass         int64
MS Zoning          object
Lot Frontage      float64
                   ...
Mo Sold             int64
Yr Sold             int64
Sale Type          object
Sale Condition     object
SalePrice           int64
Length: 82, dtype: object

In [74]:
missing = df.isnull().sum()

missing = missing[missing > 0].sort_values(ascending=False)

print(missing)

Series([], dtype: int64)

In [75]:
missing = df.isnull().sum()
missing = missing[missing > 0].sort_values(ascending=False)

print(missing)

Series([], dtype: int64)

In [76]:
none_cols = [
    "Pool QC",
    "Misc Feature",
    "Alley",
    "Fence",
    "Mas Vnr Type",
    "Fireplace Qu",
    "Garage Finish",
    "Garage Qual",
    "Garage Cond",
    "Garage Type",
    "Bsmt Exposure",
    "BsmtFin Type 2",
    "Bsmt Qual",
    "Bsmt Cond",
    "BsmtFin Type 1"
]

df[none_cols] = df[none_cols].fillna("None")

In [77]:
print("Total missing values:", df.isnull().sum().sum())

Total missing values: 0

In [78]:
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Shape:", df.shape)

Missing values: 0
Duplicate rows: 0
Shape: (2930, 82)

In [79]:
print("SalePrice <= 0:", (df["SalePrice"] <= 0).sum())
print("Lot Area <= 0:", (df["Lot Area"] <= 0).sum())
print("Gr Liv Area <= 0:", (df["Gr Liv Area"] <= 0).sum())
print("Year Built <= 0:", (df["Year Built"] <= 0).sum())
print("Overall Qual < 1:", (df["Overall Qual"] < 1).sum())
print("Overall Qual > 10:", (df["Overall Qual"] > 10).sum())

SalePrice <= 0: 0
Lot Area <= 0: 0
Gr Liv Area <= 0: 0
Year Built <= 0: 0
Overall Qual < 1: 0
Overall Qual > 10: 0

In [80]:
constant_cols = [
    col for col in df.columns
    if df[col].nunique() <= 1
]

print("Constant columns:", constant_cols)

Constant columns: []

In [81]:
categorical_cols = df.select_dtypes(include="object").columns.tolist()

print("Number of categorical columns:", len(categorical_cols))
print(categorical_cols)

Number of categorical columns: 44
['MS Zoning', 'Street', 'Alley', 'Lot Shape', 'Land Contour', 'Utilities', 'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1', 'Condition 2', 'Bldg Type', 'House Style', 'Roof Style', 'Roof Matl', 'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type', 'Exter Qual', 'Exter Cond', 'Foundation', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure', 'BsmtFin Type 1', 'BsmtFin Type 2', 'Heating', 'Heating QC', 'Central Air', 'Electrical', 'Kitchen Qual', 'Functional', 'Fireplace Qu', 'Garage Type', 'Garage Yr Blt', 'Garage Finish', 'Garage Qual', 'Garage Cond', 'Paved Drive', 'Pool QC', 'Fence', 'Misc Feature', 'Sale Type', 'Sale Condition']

In [82]:
numerical_cols = df.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

print("Number of numerical columns:", len(numerical_cols))

Number of numerical columns: 38

In [83]:
df["SalePrice"].describe()

count      2930.000000
mean     180796.060068
std       79886.692357
min       12789.000000
25%      129500.000000
50%      160000.000000
75%      213500.000000
max      755000.000000
Name: SalePrice, dtype: float64

In [84]:
correlation = df.corr(numeric_only=True)["SalePrice"].sort_values(ascending=False)

print(correlation)

SalePrice          1.000000
Overall Qual       0.799262
Gr Liv Area        0.706780
Garage Cars        0.647562
Garage Area        0.640138
Total Bsmt SF      0.632529
1st Flr SF         0.621676
Year Built         0.558426
Full Bath          0.545604
Year Remod/Add     0.532974
Mas Vnr Area       0.502196
TotRms AbvGrd      0.495474
Fireplaces         0.474558
BsmtFin SF 1       0.433147
Lot Frontage       0.340256
Wood Deck SF       0.327143
Open Porch SF      0.312951
Half Bath          0.285056
Bsmt Full Bath     0.275823
2nd Flr SF         0.269373
Lot Area           0.266549
Bsmt Unf SF        0.183308
Bedroom AbvGr      0.143913
Screen Porch       0.112151
Pool Area          0.068403
Mo Sold            0.035259
3Ssn Porch         0.032225
BsmtFin SF 2       0.006018
Misc Val          -0.015691
Yr Sold           -0.030569
Order             -0.031408
Bsmt Half Bath    -0.035817
Low Qual Fin SF   -0.037660
MS SubClass       -0.085092
Overall Cond      -0.101697
Kitchen AbvGr     -0.119814
Enclosed Porch    -0.128787
PID               -0.246521
Name: SalePrice, dtype: float64

In [85]:
df.head(50)

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,None,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,5,1960,1960,Hip,CompShg,BrkFace,Plywood,Stone,112.0,TA,TA,CBlock,TA,Gd,Gd,BLQ,639.0,Unf,0.0,441.0,1080.0,GasA,Fa,Y,SBrkr,1656,0,0,1656,1.0,0.0,1,0,3,1,TA,7,Typ,2,Gd,Attchd,1960.0,Fin,2.0,528.0,TA,TA,P,210,62,0,0,0,0,None,None,None,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,Norm,1Fam,1Story,5,6,1961,1961,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,CBlock,TA,TA,No,Rec,468.0,LwQ,144.0,270.0,882.0,GasA,TA,Y,SBrkr,896,0,0,896,0.0,0.0,1,0,2,1,TA,5,Typ,0,None,Attchd,1961.0,Unf,1.0,730.0,TA,TA,Y,140,0,0,0,120,0,None,MnPrv,None,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,None,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,6,1958,1958,Hip,CompShg,Wd Sdng,Wd Sdng,BrkFace,108.0,TA,TA,CBlock,TA,TA,No,ALQ,923.0,Unf,0.0,406.0,1329.0,GasA,TA,Y,SBrkr,1329,0,0,1329,0.0,0.0,1,1,3,1,Gd,6,Typ,0,None,Attchd,1958.0,Unf,1.0,312.0,TA,TA,Y,393,36,0,0,0,0,None,None,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,None,Reg,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,7,5,1968,1968,Hip,CompShg,BrkFace,BrkFace,None,0.0,Gd,TA,CBlock,TA,TA,No,ALQ,1065.0,Unf,0.0,1045.0,2110.0,GasA,Ex,Y,SBrkr,2110,0,0,2110,1.0,0.0,2,1,3,1,Ex,8,Typ,2,TA,Attchd,1968.0,Fin,2.0,522.0,TA,TA,Y,0,0,0,0,0,0,None,None,None,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,5,5,1997,1998,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,PConc,Gd,TA,No,GLQ,791.0,Unf,0.0,137.0,928.0,GasA,Gd,Y,SBrkr,928,701,0,1629,0.0,0.0,2,1,3,1,TA,6,Typ,1,TA,Attchd,1997.0,Fin,2.0,482.0,TA,TA,Y,212,34,0,0,0,0,None,MnPrv,None,0,3,2010,WD,Normal,189900
5,6,527105030,60,RL,78.0,9978,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,6,1998,1998,Gable,CompShg,VinylSd,VinylSd,BrkFace,20.0,TA,TA,PConc,TA,TA,No,GLQ,602.0,Unf,0.0,324.0,926.0,GasA,Ex,Y,SBrkr,926,678,0,1604,0.0,0.0,2,1,3,1,Gd,7,Typ,1,Gd,Attchd,1998.0,Fin,2.0,470.0,TA,TA,Y,360,36,0,0,0,0,None,None,None,0,6,2010,WD,Normal,195500
6,7,527127150,120,RL,41.0,4920,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,StoneBr,Norm,Norm,TwnhsE,1Story,8,5,2001,2001,Gable,CompShg,CemntBd,CmentBd,None,0.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,616.0,Unf,0.0,722.0,1338.0,GasA,Ex,Y,SBrkr,1338,0,0,1338,1.0,0.0,2,0,2,1,Gd,6,Typ,0,None,Attchd,2001.0,Fin,2.0,582.0,TA,TA,Y,0,0,170,0,0,0,None,None,None,0,4,2010,WD,Normal,213500
7,8,527145080,120,RL,43.0,5005,Pave,None,IR1,HLS,AllPub,Inside,Gtl,StoneBr,Norm,Norm,TwnhsE,1Story,8,5,1992,1992,Gable,CompShg,HdBoard,HdBoard,None,0.0,Gd,TA,PConc,Gd,TA,No,ALQ,263.0,Unf,0.0,1017.0,1280.0,GasA,Ex,Y,SBrkr,1280,0,0,1280,0.0,0.0,2,0,2,1,Gd,5,Typ,0,None,Attchd,1992.0,RFn,2.0,506.0,TA,TA,Y,0,82,0,0,144,0,None,None,None,0,1,2010,WD,Normal,191500
8,9,527146030,120,RL,39.0,5389,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,StoneBr,Norm,Norm,TwnhsE,1Story,8,5,1995,1996,Gable,CompShg,CemntBd,CmentBd,None,0.0,Gd,TA,PConc,Gd,TA,No,GLQ,1180.0,Unf,0.0,415.0,1595.0,GasA,Ex,Y,SBrkr,1616,0,0,1616,1.0,0.0,2,0,2,1,Gd,5,Typ,1,TA,Attchd,1995.0,RFn,2.0,608.0,TA,TA,Y,237,152,0,0,0,0,None,None,None,0,3,2010,WD,Normal,236500
9,10,527162130,60,RL,60.0,7500,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,7,5,1999,1999,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,PConc,TA,TA,No,Unf,0.0,Unf,0.0,994.0,994.0,GasA,Gd,Y,SBrkr,1028,776,0,1804,0.0,0.0,2,1,3,1,Gd,7,Typ,1,TA,Attchd,1999.0,Fin,2.0,442.0,TA,TA,Y,140,60,0,0,0,0,None,None,None,0,6,2010,WD,Normal,189000
10,11,527163010,60,RL,75.0,10000,Pave,None,IR1,Lvl,AllPub,Corner,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,5,1993,1994,Gable,CompShg,HdBoard,HdBoard,None,0.0,TA,TA,PConc,Gd,TA,No,Unf,0.0,Unf,0.0,763.0,763.0,GasA,Gd,Y,SBrkr,763,892,0,1655,0.0,0.0,2,1,3,1,TA,7,Typ,1,TA,Attchd,1993.0,Fin,2.0,440.0,TA,TA,Y,157,84,0,0,0,0,None,None,None,0,4,2010,WD,Normal,175900
11,12,527165230,20,RL,68.0,7980,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,1Story,6,7,1992,2007,Gable,CompShg,HdBoard,HdBoard,None,0.0,TA,Gd,PConc,Gd,TA,No,ALQ,935.0,Unf,0.0,233.0,1168.0,GasA,Ex,Y,SBrkr,1187,0,0,1187,1.0,0.0,2,0,3,1,TA,6,Typ,0,None,Attchd,1992.0,Fin,2.0,420.0,TA,TA,Y,483,21,0,0,0,0,None,GdPrv,Shed,500,3,2010,WD,Normal,185000
12,13,527166040,60,RL,63.0,8402,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,5,1998,1998,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,PConc,Gd,TA,No,Unf,0.0,Unf,0.0,789.0,789.0,GasA,Gd,Y,SBrkr,789,676,0,1465,0.0,0.0,2,1,3,1,TA,7,Typ,1,Gd,Attchd,1998.0,Fin,2.0,393.0,TA,TA,Y,0,75,0,0,0,0,None,None,None,0,5,2010,WD,Normal,180400
13,14,527180040,20,RL,85.0,10176,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,1Story,7,5,1990,1990,Gable,CompShg,HdBoard,HdBoard,None,0.0,TA,TA,PConc,Gd,TA,Gd,GLQ,637.0,Unf,0.0,663.0,1300.0,GasA,Gd,Y,SBrkr,1341,0,0,1341,1.0,0.0,1,1,2,1,Gd,5,Typ,1,Po,Attchd,1990.0,Unf,2.0,506.0,TA,TA,Y,192,0,0,0,0,0,None,None,None,0,2,2010,WD,Normal,171500
14,15,527182190,120,RL,68.0,6820,Pave,None,IR1,Lvl,AllPub,Corner,Gtl,StoneBr,Norm,Norm,TwnhsE,1Story,8,5,1985,1985,Gable,CompShg,HdBoard,HdBoard,None,0.0,Gd,TA,PConc,Gd,TA,Av,GLQ,368.0,BLQ,1120.0,0.0,1488.0,GasA,TA,Y,SBrkr,1502,0,0,1502,1.0,0.0,1,1,1,1,Gd,4,Typ,0,None,Attchd,1985.0,RFn,2.0,528.0,TA,TA,Y,0,54,0,0,140,0,None,None,None,0,6,2010,WD,Normal,212000
15,16,527216070,60,RL,47.0,53504,Pave,None,IR2,HLS,AllPub,CulDSac,Mod,StoneBr,Norm,Norm,1Fam,2Story,8,5,2003,2003,Hip,CompShg,CemntBd,Wd Shng,BrkFace,603.0,Ex,TA,PConc,Gd,TA,Gd,ALQ,1416.0,Unf,0.0,234.0,1650.0,GasA,Ex,Y,SBrkr,1690,1589,0,3279,1.0,0.0,3,1,4,1,Ex,12,Mod,1,Gd,BuiltIn,2003.0,Fin,3.0,841.0,TA,TA,Y,503,36,0,0,210,0,None,None,None,0,6,2010,WD,Normal,538000
16,17,527225035,50,RL,152.0,12134,Pave,None,IR1,Bnk,AllPub,Inside,Mod,Gilbert,Norm,Norm,1Fam,1.5Fin,8,7,1988,2005,Gable,CompShg,Wd Sdng,Wd Sdng,None,0.0,Gd,TA,Wood,Gd,TA,Av,GLQ,427.0,Unf,0.0,132.0,559.0,GasA,Gd,Y,SBrkr,1080,672,0,1752,0.0,0.0,2,0,4,1,TA,8,Typ,0,None,Basment,1988.0,RFn,2.0,492.0,TA,TA,Y,325,12,0,0,0,0,None,None,None,0,6,2010,WD,Normal,164000
17,18,527258010,20,RL,88.0,11394,Pave,None,Reg,Lvl,AllPub,Corner,Gtl,StoneBr,Norm,Norm,1Fam,1Story,9,2,2010,2010,Hip,CompShg,VinylSd,VinylSd,Stone,350.0,Gd,TA,PConc,Ex,TA,Av,GLQ,1445.0,Unf,0.0,411.0,1856.0,GasA,Ex,Y,SBrkr,1856,0,0,1856,1.0,0.0,1,1,1,1,Ex,8,Typ,1,Ex,Attchd,2010.0,Fin,3.0,834.0,TA,TA,Y,113,0,0,0,0,0,None,None,None,0,6,2010,New,Partial,394432
18,19,527276150,20,RL,140.0,19138,Pave,None,Reg,Lvl,AllPub,Corner,Gtl,Gilbert,Norm,Norm,1Fam,1Story,4,5,1951,1951,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,CBlock,TA,TA,No,LwQ,120.0,Unf,0.0,744.0,864.0,GasA,Ex,Y,SBrkr,864,0,0,864,0.0,0.0,1,0,2,1,TA,4,Typ,0,None,Detchd,1951.0,Unf,2.0,400.0,TA,TA,Y,0,0,0,0,0,0,None,None,None,0,6,2010,WD,Normal,141000
19,20,527302110,20,RL,85.0,13175,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,6,6,1978,1988,Gable,CompShg,Plywood,Plywood,Stone,119.0,TA,TA,CBlock,Gd,TA,No,ALQ,790.0,Rec,163.0,589.0,1542.0,GasA,TA,Y,SBrkr,2073,0,0,2073,1.0,0.0,2,0,3,1,TA,7,Min1,2,TA,Attchd,1978.0,Unf,2.0,500.0,TA,TA,Y,349,0,0,0,0,0,None,MnPrv,None,0,2,2010,WD,Normal,210000
20,21,527358140,20,RL,105.0,11751,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,6,6,1977,1977,Hip,CompShg,Plywood,Plywood,BrkFace,480.0,TA,TA,CBlock,Gd,TA,No,BLQ,705.0,Unf,0.0,1139.0,1844.0,GasA,Ex,Y,SBrkr,1844,0,0,1844,0.0,0.0,2,0,3,1,TA,7,Typ,1,TA,Attchd,1977.0,RFn,2.0,546.0,TA,TA,Y,0,122,0,0,0,0,None,MnPrv,None,0,1,2010,COD,Normal,190000
21,22,527358200,85,RL,85.0,10625,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,SFoyer,7,6,1974,1974,Gable,CompShg,Plywood,Plywood,BrkFace,81.0,TA,TA,CBlock,Gd,TA,Gd,GLQ,885.0,LwQ,168.0,0.0,1053.0,GasA,TA,Y,SBrkr,1173,0,0,1173,1.0,0.0,2,0,3,1,Gd,6,Typ,2,TA,Attchd,1974.0,RFn,2.0,528.0,TA,TA,Y,0,120,0,0,0,0,None,MnPrv,None,0,1,2010,WD,Family,170000
22,23,527368020,60,FV,68.0,7500,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,Somerst,Norm,Norm,1Fam,2Story,7,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,None,0.0,Gd,TA,PConc,Gd,TA,No,GLQ,533.0,Unf,0.0,281.0,814.0,GasA,Ex,Y,SBrkr,814,860,0,1674,1.0,0.0,2,1,3,1,Gd,7,Typ,0,None,Attchd,2000.0,RFn,2.0,663.0,TA,TA,Y,0,96,0,0,0,0,None,None,None,0,1,2010,WD,Normal,216000
23,24,527402200,20,RL,68.0,11241,Pave,None,IR1,Lvl,AllPub,CulDSac,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,7,1970,1970,Gable,CompShg,Wd Sdng,Wd Sdng,BrkFace,180.0,TA,TA,CBlock,TA,TA,No,ALQ,578.0,Unf,0.0,426.0,1004.0,GasA,Ex,Y,SBrkr,1004,0,0,1004,1.0,0.0,1,0,2,1,TA,5,Typ,1,TA,Attchd,1970.0,Fin,2.0,480.0,TA,TA,Y,0,0,0,0,0,0,None,None,Shed,700,3,2010,WD,Normal,149000
24,25,527402250,20,RL,68.0,12537,Pave,None,IR1,Lvl,AllPub,CulDSac,Gtl,NAmes,Norm,Norm,1Fam,1Story,5,6,1971,2008,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,CBlock,TA,TA,No,GLQ,734.0,Unf,0.0,344.0,1078.0,GasA,Ex,Y,SBrkr,1078,0,0,1078,1.0,0.0,1,1,3,1,TA,6,Typ,1,Fa,Attchd,1971.0,Fin,2.0,500.0,TA,TA,Y,0,0,0,0,0,0,None,None,None,0,4,2010,WD,Normal,149900
25,26,527403020,20,RL,65.0,8450,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,5,6,1968,1968,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,CBlock,TA,TA,No,BLQ,775.0,Unf,0.0,281.0,1056.0,GasA,Ex,Y,SBrkr,1056,0,0,1056,1.0,0.0,1,0,3,1,TA,6,Typ,1,Fa,Attchd,1968.0,Unf,1.0,304.0,TA,TA,Y,0,85,184,0,0,0,None,None,None,0,7,2010,WD,Normal,142000
26,27,527404120,20,RL,70.0,8400,Pave,None,Reg,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,4,5,1970,1970,Gable,CompShg,Plywood,Plywood,None,0.0,TA,TA,CBlock,TA,TA,No,ALQ,804.0,Rec,78.0,0.0,882.0,GasA,TA,Y,SBrkr,882,0,0,882,1.0,0.0,1,0,2,1,TA,4,Typ,0,None,Attchd,1970.0,Fin,2.0,525.0,TA,TA,Y,240,0,0,0,0,0,None,MnPrv,None,0,4,2010,WD,Normal,126000
27,28,527425090,20,RL,70.0,10500,Pave,None,Reg,Lvl,AllPub,FR2,Gtl,NAmes,Norm,Norm,1Fam,1Story,4,5,1971,1971,Gable,CompShg,HdBoard,HdBoard,None,0.0,TA,TA,CBlock,TA,TA,No,ALQ,432.0,Unf,0.0,432.0,864.0,GasA,TA,Y,SBrkr,864,0,0,864,0.0,0.0,1,0,3,1,TA,5,Typ,1,Po,None,None,None,0.0,0.0,None,None,Y,0,0,0,0,0,0,None,None,None,0,4,2010,ConLI,Normal,115000
28,29,527427230,120,RH,26.0,5858,Pave,None,IR1,Lvl,AllPub,FR2,Gtl,NAmes,Norm,Norm,TwnhsE,1Story,7,5,1999,1999,Gable,CompShg,MetalSd,MetalSd,None,0.0,Gd,TA,PConc,Gd,TA,No,GLQ,1051.0,BLQ,0.0,354.0,1405.0,GasA,Ex,Y,SBrkr,1337,0,0,1337,1.0,0.0,2,0,2,1,Gd,5,Typ,1,Fa,Attchd,1999.0,Fin,2.0,511.0,TA,TA,Y,203,68,0,0,0,0,None,None,None,0,6,2010,WD,Normal,184000
29,30,527451180,160,RM,21.0,1680,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,BrDale,Norm,Norm,Twnhs,2Story,6,5,1971,1971,Gable,CompShg,HdBoard,HdBoard,BrkFace,504.0,TA,TA,CBlock,TA,TA,No,Rec,156.0,Unf,0.0,327.0,483.0,GasA,TA,Y,SBrkr,483,504,0,987,0.0,0.0,1,1,2,1,TA,5,Typ,0,None,Detchd,1971.0,Unf,1.0,264.0,TA,TA,Y,275,0,0,0,0,0,None,None,None,0,2,2010,COD,Normal,96000
30,31,527451330,160,RM,21.0,1680,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,BrDale,Norm,Norm,Twnhs,2Story,5,5,1971,1971,Gable,CompShg,HdBoard,HdBoard,BrkFace,492.0,TA,TA,CBlock,TA,TA,No,Rec,300.0,Unf,0.0,225.0,525.0,GasA,TA,Y,SBrkr,525,567,0,1092,0.0,0.0,1,1,3,1,TA,6,Typ,0,None,Detchd,1997.0,Unf,1.0,320.0,TA,TA,Y,0,0,0,0,0,0,None,None,None,0,3,2010,WD,Normal,105500
31,32,527451410,160,RM,21.0,1680,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,BrDale,Norm,Norm,Twnhs,2Story,6,5,1971,1971,Gable,CompShg,HdBoard,ImStucc,BrkFace,381.0,TA,TA,CBlock,TA,TA,No,Unf,0.0,Unf,0.0,525.0,525.0,GasA,TA,Y,SBrkr,525,567,0,1092,0.0,0.0,1,1,3,1,TA,6,Typ,0,None,Detchd,1971.0,Unf,1.0,264.0,TA,TA,Y,0,0,0,0,0,0,None,None,None,0,3,2010,WD,Family,88000
32,33,527452190,120,RL,53.0,4043,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,NPkVill,Norm,Norm,TwnhsE,1Story,6,5,1977,1977,Gable,CompShg,Plywood,Plywood,None,0.0,TA,TA,CBlock,Gd,TA,No,ALQ,360.0,Unf,0.0,709.0,1069.0,GasA,TA,Y,SBrkr,1069,0,0,1069,0.0,0.0,2,0,2,1,TA,4,Typ,1,Fa,Attchd,1977.0,RFn,2.0,440.0,TA,TA,Y,0,55,0,0,165,0,None,None,None,0,7,2010,WD,Normal,127500
33,34,527453130,160,RL,24.0,2280,Pave,None,Reg,Lvl,AllPub,FR2,Gtl,NPkVill,Norm,Norm,Twnhs,2Story,6,6,1975,1975,Gable,CompShg,Plywood,Brk Cmn,None,0.0,TA,TA,CBlock,TA,TA,No,ALQ,514.0,Unf,0.0,341.0,855.0,GasA,TA,Y,SBrkr,855,601,0,1456,0.0,0.0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,1975.0,Unf,2.0,440.0,TA,TA,Y,173,0,0,0,0,0,None,None,None,0,6,2010,WD,Normal,149900
34,35,527453150,120,RL,24.0,2280,Pave,None,Reg,Lvl,AllPub,FR2,Gtl,NPkVill,Norm,Norm,Twnhs,1Story,7,6,1975,1975,Gable,CompShg,Plywood,Brk Cmn,None,0.0,TA,TA,CBlock,Gd,TA,No,Unf,0.0,Unf,0.0,836.0,836.0,GasA,Ex,Y,SBrkr,836,0,0,836,0.0,0.0,1,0,2,1,TA,4,Typ,0,None,Attchd,1975.0,Unf,1.0,308.0,TA,TA,Y,0,30,0,0,0,0,None,None,None,0,6,2010,WD,Normal,120000
35,36,527454200,160,RL,24.0,2280,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,NPkVill,Norm,Norm,Twnhs,2Story,6,5,1978,1978,Gable,CompShg,Plywood,Brk Cmn,None,0.0,TA,TA,CBlock,Gd,TA,No,ALQ,311.0,Unf,0.0,544.0,855.0,GasA,Fa,Y,SBrkr,855,601,0,1456,0.0,0.0,2,1,3,1,TA,7,Typ,1,TA,Attchd,1978.0,Unf,2.0,440.0,TA,TA,Y,26,0,0,0,0,0,None,None,None,0,7,2010,WD,Normal,146000
36,37,528108120,60,RL,102.0,12858,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,NridgHt,Norm,Norm,1Fam,2Story,9,5,2009,2010,Gable,CompShg,VinylSd,VinylSd,Stone,162.0,Ex,TA,PConc,Ex,TA,No,Unf,0.0,Unf,0.0,1590.0,1590.0,GasA,Ex,Y,SBrkr,1627,707,0,2334,0.0,0.0,2,1,3,1,Ex,10,Typ,1,Gd,Attchd,2009.0,Fin,3.0,751.0,TA,TA,Y,144,133,0,0,0,0,None,None,None,0,1,2010,New,Partial,376162
37,38,528112020,20,RL,98.0,11478,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,NridgHt,Norm,Norm,1Fam,1Story,8,5,2007,2008,Gable,CompShg,VinylSd,VinylSd,Stone,200.0,Gd,TA,PConc,Ex,TA,No,GLQ,1218.0,Unf,0.0,486.0,1704.0,GasA,Ex,Y,SBrkr,1704,0,0,1704,1.0,0.0,2,0,3,1,Gd,7,Typ,1,Gd,Attchd,2008.0,RFn,3.0,772.0,TA,TA,Y,0,50,0,0,0,0,None,None,None,0,5,2010,WD,Normal,306000
38,39,528120060,20,RL,83.0,10159,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,NridgHt,Norm,Norm,1Fam,1Story,9,5,2009,2010,Hip,CompShg,VinylSd,VinylSd,Stone,450.0,Ex,TA,PConc,Ex,TA,Av,GLQ,1646.0,Unf,0.0,284.0,1930.0,GasA,Ex,Y,SBrkr,1940,0,0,1940,1.0,0.0,2,1,3,1,Ex,8,Typ,1,Gd,Attchd,2010.0,Fin,3.0,606.0,TA,TA,Y,168,95,0,0,0,0,None,None,None,0,4,2010,New,Partial,395192
39,40,528120090,20,RL,94.0,12883,Pave,None,IR1,Lvl,AllPub,Corner,Gtl,NridgHt,Norm,Norm,1Fam,1Story,8,5,2009,2010,Gable,CompShg,VinylSd,VinylSd,Stone,256.0,Gd,TA,PConc,Gd,TA,No,Unf,0.0,Unf,0.0,1544.0,1544.0,GasA,Ex,Y,SBrkr,1544,0,0,1544,0.0,0.0,2,0,3,1,Gd,7,Typ,0,None,Attchd,2009.0,RFn,3.0,868.0,TA,TA,Y,0,35,0,0,0,0,None,None,None,0,6,2010,New,Partial,290941
40,41,528120100,20,RL,95.0,12182,Pave,None,Reg,Lvl,AllPub,Corner,Gtl,NridgHt,Norm,Norm,1Fam,1Story,7,5,2005,2005,Gable,CompShg,VinylSd,VinylSd,BrkFace,226.0,Gd,TA,PConc,Gd,TA,Mn,BLQ,1201.0,Unf,0.0,340.0,1541.0,GasA,Ex,Y,SBrkr,1541,0,0,1541,0.0,0.0,2,0,3,1,Gd,7,Typ,1,Gd,Attchd,2005.0,RFn,2.0,532.0,TA,TA,Y,0,70,0,0,0,0,None,None,None,0,5,2010,New,Partial,220000
41,42,528120120,20,RL,90.0,11520,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,NridgHt,PosN,Norm,1Fam,1Story,9,5,2005,2005,Hip,CompShg,VinylSd,VinylSd,BrkFace,615.0,Gd,TA,PConc,Ex,TA,No,GLQ,110.0,Unf,0.0,1588.0,1698.0,GasA,Ex,Y,SBrkr,1698,0,0,1698,0.0,0.0,2,0,3,1,Ex,7,Typ,1,Gd,Attchd,2005.0,Fin,3.0,730.0,TA,TA,Y,192,74,0,0,0,0,None,None,None,0,6,2010,WD,Normal,275000
42,43,528138020,20,RL,79.0,14122,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,NridgHt,Norm,Norm,1Fam,1Story,8,5,2005,2006,Hip,CompShg,CemntBd,CmentBd,BrkFace,240.0,Gd,TA,PConc,Ex,TA,No,GLQ,28.0,Unf,0.0,1794.0,1822.0,GasA,Ex,Y,SBrkr,1822,0,0,1822,0.0,0.0,2,0,3,1,Ex,8,Typ,1,Gd,Attchd,2005.0,RFn,3.0,678.0,TA,TA,Y,0,119,0,0,0,0,None,None,None,0,2,2010,WD,Normal,259000
43,44,528138060,20,RL,70.0,10171,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,NridgHt,Norm,Norm,1Fam,1Story,7,5,2004,2004,Gable,CompShg,VinylSd,VinylSd,BrkFace,168.0,Gd,TA,PConc,Gd,TA,No,GLQ,2.0,Unf,0.0,1515.0,1517.0,GasA,Ex,Y,SBrkr,1535,0,0,1535,0.0,0.0,2,0,3,1,Gd,7,Typ,0,None,Attchd,2004.0,RFn,2.0,532.0,TA,TA,Y,0,0,0,0,0,0,None,None,None,0,3,2010,WD,Normal,214000
44,45,528150070,20,RL,100.0,12919,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,NridgHt,Norm,Norm,1Fam,1Story,9,5,2009,2010,Hip,CompShg,VinylSd,VinylSd,Stone,760.0,Ex,TA,PConc,Ex,TA,Gd,GLQ,2188.0,Unf,0.0,142.0,2330.0,GasA,Ex,Y,SBrkr,2364,0,0,2364,1.0,0.0,2,1,2,1,Ex,11,Typ,2,Gd,Attchd,2009.0,Fin,3.0,820.0,TA,TA,Y,0,67,0,0,0,0,None,None,None,0,3,2010,New,Partial,611657
45,46,528175010,120,RL,44.0,6371,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,NridgHt,Norm,Norm,TwnhsE,1Story,7,5,2009,2010,Gable,CompShg,VinylSd,VinylSd,Stone,128.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,733.0,Unf,0.0,625.0,1358.0,GasA,Ex,Y,SBrkr,1358,0,0,1358,1.0,0.0,2,0,2,1,Gd,6,Typ,1,Gd,Attchd,2010.0,RFn,2.0,484.0,TA,TA,Y,192,35,0,0,0,0,None,None,None,0,6,2010,New,Partial,224000
46,47,528176010,20,RL,110.0,14300,Pave,None,Reg,HLS,AllPub,Inside,Mod,NridgHt,Norm,Norm,1Fam,1Story,9,5,2003,2004,Hip,CompShg,VinylSd,VinylSd,BrkFace,1095.0,Ex,TA,PConc,Ex,TA,Gd,GLQ,1373.0,Unf,0.0,1473.0,2846.0,GasA,Ex,Y,SBrkr,2696,0,0,2696,1.0,0.0,2,1,3,1,Ex,10,Typ,2,Gd,Attchd,2003.0,Fin,3.0,958.0,TA,TA,Y,220,150,0,0,0,0,None,None,None,0,6,2010,WD,Normal,500000
47,48,528176070,60,RL,105.0,13650,Pave,None,Reg,Lvl,AllPub,Corner,Gtl,NridgHt,Norm,Norm,1Fam,2Story,8,5,2002,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,232.0,Gd,TA,PConc,Gd,TA,Gd,GLQ,578.0,Unf,0.0,1093.0,1671.0,GasA,Ex,Y,SBrkr,1687,563,0,2250,1.0,0.0,2,1,3,1,Gd,7,Typ,1,Ex,Attchd,2002.0,Fin,3.0,756.0,TA,TA,Y,238,130,0,0,0,0,None,None,None,0,6,2010,WD,Normal,320000
48,49,528180070,120,RL,61.0,7658,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,NridgHt,Norm,Norm,TwnhsE,1Story,9,5,2005,2005,Hip,CompShg,MetalSd,MetalSd,BrkFace,412.0,Ex,TA,PConc,Ex,TA,No,GLQ,456.0,Unf,0.0,1296.0,1752.0,GasA,Ex,Y,SBrkr,1752,0,0,1752,1.0,0.0,2,0,2,1,Ex,6,Typ,1,Gd,Attchd,2005.0,RFn,2.0,576.0,TA,TA,Y,196,82,0,0,0,0,None,None,None,0,2,2010,WD,Normal,319900
49,50,528181050,120,RL,41.0,7132,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,NridgHt,Norm,Norm,TwnhsE,1Story,8,5,2006,2006,Gable,CompShg,VinylSd,VinylSd,Stone,178.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,24.0,Unf,0.0,1346.0,1370.0,GasA,Ex,Y,SBrkr,1370,0,0,1370,0.0,0.0,2,0,2,1,Gd,6,Typ,1,Gd,Attchd,2006.0,RFn,2.0,484.0,TA,TA,Y,120,49,0,0,0,0,None,None,None,0,4,2010,WD,Normal,205000

In [86]:
df["Sale Condition"].unique()

array(['Normal', 'Partial', 'Family', 'Abnorml', 'Alloca', 'AdjLand'],
      dtype=object)

In [87]:
#Separate Features (X) and Target (y)#
#CREATE X - X contains all the information we will give to the model.#

In [88]:
X = df.drop("SalePrice", axis=1)

In [89]:
#CREATE Y - y contains the answer we want the model to learn to predict.#

In [90]:
y = df["SalePrice"]

In [91]:
X.head()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition
0,1,526301100,20,RL,141.0,31770,Pave,None,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,5,1960,1960,Hip,CompShg,BrkFace,Plywood,Stone,112.0,TA,TA,CBlock,TA,Gd,Gd,BLQ,639.0,Unf,0.0,441.0,1080.0,GasA,Fa,Y,SBrkr,1656,0,0,1656,1.0,0.0,1,0,3,1,TA,7,Typ,2,Gd,Attchd,1960.0,Fin,2.0,528.0,TA,TA,P,210,62,0,0,0,0,None,None,None,0,5,2010,WD,Normal
1,2,526350040,20,RH,80.0,11622,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,Norm,1Fam,1Story,5,6,1961,1961,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,CBlock,TA,TA,No,Rec,468.0,LwQ,144.0,270.0,882.0,GasA,TA,Y,SBrkr,896,0,0,896,0.0,0.0,1,0,2,1,TA,5,Typ,0,None,Attchd,1961.0,Unf,1.0,730.0,TA,TA,Y,140,0,0,0,120,0,None,MnPrv,None,0,6,2010,WD,Normal
2,3,526351010,20,RL,81.0,14267,Pave,None,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,6,1958,1958,Hip,CompShg,Wd Sdng,Wd Sdng,BrkFace,108.0,TA,TA,CBlock,TA,TA,No,ALQ,923.0,Unf,0.0,406.0,1329.0,GasA,TA,Y,SBrkr,1329,0,0,1329,0.0,0.0,1,1,3,1,Gd,6,Typ,0,None,Attchd,1958.0,Unf,1.0,312.0,TA,TA,Y,393,36,0,0,0,0,None,None,Gar2,12500,6,2010,WD,Normal
3,4,526353030,20,RL,93.0,11160,Pave,None,Reg,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,7,5,1968,1968,Hip,CompShg,BrkFace,BrkFace,None,0.0,Gd,TA,CBlock,TA,TA,No,ALQ,1065.0,Unf,0.0,1045.0,2110.0,GasA,Ex,Y,SBrkr,2110,0,0,2110,1.0,0.0,2,1,3,1,Ex,8,Typ,2,TA,Attchd,1968.0,Fin,2.0,522.0,TA,TA,Y,0,0,0,0,0,0,None,None,None,0,4,2010,WD,Normal
4,5,527105010,60,RL,74.0,13830,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,5,5,1997,1998,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,PConc,Gd,TA,No,GLQ,791.0,Unf,0.0,137.0,928.0,GasA,Gd,Y,SBrkr,928,701,0,1629,0.0,0.0,2,1,3,1,TA,6,Typ,1,TA,Attchd,1997.0,Fin,2.0,482.0,TA,TA,Y,212,34,0,0,0,0,None,MnPrv,None,0,3,2010,WD,Normal

In [92]:
y.head()

0    215000
1    105000
2    172000
3    244000
4    189900
Name: SalePrice, dtype: int64

In [93]:
#Check their shapes#

In [94]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (2930, 81)
y shape: (2930,)

In [95]:
#Before processing - Now identify numerical and categorical features in X#

In [96]:
numeric_features = X.select_dtypes(
    include=["int64", "float64"]
).columns

categorical_features = X.select_dtypes(
    include=["object"]
).columns

In [97]:
#Check#

In [98]:
print("Numerical features:", len(numeric_features))
print("Categorical features:", len(categorical_features))

Numerical features: 37
Categorical features: 44

In [99]:
#Remove obvious identifier columns - Order and PID identify properties/records, but they don't represent meaningful 
housing characteristics. We generally don't want the model learning patterns from those identifiers.#

SyntaxError: unterminated string literal (detected at line 2) (2377131787.py, line 2)

In [100]:
X = X.drop(columns=["Order", "PID"])

In [101]:
X.shape

(2930, 79)

In [102]:
#Now we're ready for train/test split. This is where your sklearn import comes in.#

In [103]:
from sklearn.model_selection import train_test_split

In [104]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [105]:
#This means: 80% → training, 20% → testing. Check:#

In [106]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (2344, 79)
X_test: (586, 79)
y_train: (2344,)
y_test: (586,)

In [107]:
#Import preprocessing tools#

In [108]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

In [109]:
#Create the preprocessing system#

In [110]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        )
    ],
    remainder="passthrough"
)

In [111]:
#Import Linear Regression#

In [112]:
from sklearn.linear_model import LinearRegression

In [113]:
model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("regressor", LinearRegression())
    ]
)

In [114]:
#Train the model#

In [115]:
from sklearn.impute import SimpleImputer

In [116]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            Pipeline(
                steps=[
                    ("imputer", SimpleImputer(strategy="most_frequent")),
                    ("encoder", OneHotEncoder(handle_unknown="ignore"))
                ]
            ),
            categorical_features
        ),
        (
            "numerical",
            SimpleImputer(strategy="median"),
            numeric_features
        )
    ]
)

In [117]:
#Recreate the model#

In [118]:
model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("regressor", LinearRegression())
    ]
)

In [119]:
#Train again#

In [121]:
numeric_features = X_train.select_dtypes(
    include=["int64", "float64"]
).columns

categorical_features = X_train.select_dtypes(
    include=["object"]
).columns

print("Number of numerical features:", len(numeric_features))
print("Number of categorical features:", len(categorical_features))

Number of numerical features: 35
Number of categorical features: 44

In [122]:
print("Order" in X_train.columns)
print("PID" in X_train.columns)

False
False

In [123]:
#Recreate Processor#

In [124]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

In [125]:
from sklearn.linear_model import LinearRegression

In [126]:
model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("regressor", LinearRegression())
    ]
)

In [127]:
#Train The Model Again#

In [166]:
# Remove identifier columns from X
X = X.drop(columns=["Order", "PID"], errors="ignore")

# Create the train/test split again
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (2344, 79)
X_test: (586, 79)
y_train: (2344,)
y_test: (586,)

In [167]:
# Identify numerical and categorical columns

numeric_features = X_train.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_features = X_train.select_dtypes(
    include=["object"]
).columns.tolist()

print("Numerical features:", len(numeric_features))
print("Categorical features:", len(categorical_features))

Numerical features: 35
Categorical features: 44

In [168]:
print("Order in X_train:", "Order" in X_train.columns)
print("PID in X_train:", "PID" in X_train.columns)

Order in X_train: False
PID in X_train: False

In [169]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            Pipeline([
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("encoder", OneHotEncoder(handle_unknown="ignore"))
            ]),
            categorical_features
        ),
        (
            "numerical",
            SimpleImputer(strategy="median"),
            numeric_features
        )
    ]
)

In [170]:
from sklearn.linear_model import LinearRegression

model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", LinearRegression())
])

In [171]:
#NOW TRAIN AGAIN#

In [172]:
model.fit(X_train, y_train)

TypeError: Encoders require their input argument must be uniformly strings or numbers. Got ['float', 'str']

In [173]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer
from sklearn.linear_model import LinearRegression

In [174]:
numeric_features = X_train.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_features = X_train.select_dtypes(
    include=["object"]
).columns.tolist()

print("Numerical:", len(numeric_features))
print("Categorical:", len(categorical_features))

Numerical: 35
Categorical: 44

In [175]:
categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("to_string", FunctionTransformer(lambda x: x.astype(str))),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

In [176]:
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median"))
])

In [177]:
preprocessor = ColumnTransformer([
    ("categorical", categorical_pipeline, categorical_features),
    ("numerical", numeric_pipeline, numeric_features)
])

In [178]:
model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", LinearRegression())
])

In [179]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('to_string',
                                                                   FunctionTransformer(func=<function <lambda> at 0x000001FBC7C15800>)),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['MS Zoning', 'Street',
                                                   'Alley', 'Lot Shape',
                                                   'Land Contour', 'Utilities',
                                                   'Lot C...
                                                   'Year Remod/Add',
                                                   'Mas Vnr Area',
                                                   'BsmtFin SF 1',
                                                   'BsmtFin SF 2',
                                                   'Bsmt Unf SF',
                                                   'Total Bsmt SF',
                                                   '1st Flr SF', '2nd Flr SF',
                                                   'Low Qual Fin SF',
                                                   'Gr Liv Area',
                                                   'Bsmt Full Bath',
                                                   'Bsmt Half Bath',
                                                   'Full Bath', 'Half Bath',
                                                   'Bedroom AbvGr',
                                                   'Kitchen AbvGr',
                                                   'TotRms AbvGrd',
                                                   'Fireplaces', 'Garage Cars',
                                                   'Garage Area',
                                                   'Wood Deck SF',
                                                   'Open Porch SF',
                                                   'Enclosed Porch',
                                                   '3Ssn Porch', ...])])),
                ('regressor', LinearRegression())])

In [180]:
#MAKE PREDICTIONS#

In [181]:
y_pred = model.predict(X_test)

In [182]:
#Look at the first 10 predictions#

In [183]:
y_pred[:10]

array([142230.33398861, 105444.44450845, 188063.56548912, 133485.34012167,
       131847.28709218, 190125.47006915, 153367.50715095, 147554.69617853,
       102407.28739912, 338448.23304069])

In [184]:
#Compare actual prices with predicted prices#

In [185]:
comparison = pd.DataFrame({
    "Actual SalePrice": y_test.values,
    "Predicted SalePrice": y_pred
})

comparison.head(10)

   Actual SalePrice  Predicted SalePrice
0            161000        142230.333989
1            116000        105444.444508
2            196500        188063.565489
3            123600        133485.340122
4            126000        131847.287092
5            174190        190125.470069
6            200000        153367.507151
7            148500        147554.696179
8             88750        102407.287399
9            409900        338448.233041

In [186]:
#Import the evaluation Matrix#

In [187]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [188]:
#Calculate the Matrixes#

In [189]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

In [190]:
#Display the result#

In [191]:
print("Model Evaluation")
print("------------------------")
print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R²  :", r2)

Model Evaluation
------------------------
MAE : 17849.153424762768
MSE : 922770239.3531944
RMSE: 30377.133494673166
R²  : 0.8849061773867416

In [192]:
#NOTE#

╔══════════════════════════════════════════════════════════════╗
║        MACHINE LEARNING MODEL EVALUATION — QUICK NOTE        ║
║              Ames Housing Price Prediction                   ║
╚══════════════════════════════════════════════════════════════╝

MODEL:
Linear Regression

TARGET:
SalePrice — the house price we want the model to predict.

PREDICTION:
y_pred = model.predict(X_test)

The model uses the house characteristics in X_test to predict
the SalePrice of houses it has not seen during training.


──────────────────────────────────────────────────────────────
1. MAE — Mean Absolute Error
──────────────────────────────────────────────────────────────

MAE tells us the average amount by which the model's predictions
are different from the actual house prices.

Our result:
MAE = 17,849.15

Meaning:
The model's predictions are approximately $17,849 away from the
actual house prices on average.

LOWER MAE = BETTER


──────────────────────────────────────────────────────────────
2. MSE — Mean Squared Error
──────────────────────────────────────────────────────────────

MSE calculates the average squared difference between predicted
prices and actual prices.

Our result:
MSE = 922,770,239.35

Because the errors are squared, the number becomes very large.
Therefore, MSE is usually less intuitive to interpret directly.

LOWER MSE = BETTER


──────────────────────────────────────────────────────────────
3. RMSE — Root Mean Squared Error
──────────────────────────────────────────────────────────────

RMSE is the square root of MSE.

It measures prediction error in the SAME UNIT as SalePrice,
making it easier to understand than MSE.

Our result:
RMSE = 30,377.13

Meaning:
The model's typical prediction error is around $30,377, with
larger errors receiving more importance.

LOWER RMSE = BETTER


──────────────────────────────────────────────────────────────
4. R² — R-Squared
──────────────────────────────────────────────────────────────

R² measures how much of the variation in house prices is
explained by the model.

Our result:
R² = 0.8849

This is approximately:

88.49%

Meaning:
The model explains about 88.5% of the variation in house
prices in the TEST dataset.

Generally:
R² closer to 1 = better
R² closer to 0 = weaker

An R² of 0.8849 is a strong result for this Linear Regression
model.


──────────────────────────────────────────────────────────────
5. ACTUAL vs PREDICTED
──────────────────────────────────────────────────────────────

ACTUAL PRICE:
The real SalePrice from the dataset.

PREDICTED PRICE:
The price estimated by our machine learning model.

Example:

Actual:     $161,000
Predicted:  $142,230

Difference:
Approximately $18,770


──────────────────────────────────────────────────────────────
6. OUR MODEL'S RESULTS
──────────────────────────────────────────────────────────────

MAE  = $17,849.15
RMSE = $30,377.13
R²   = 0.8849 (88.49%)

Overall interpretation:

The Linear Regression model is performing reasonably well.
It explains approximately 88.5% of the variation in house
prices, while its average absolute prediction error is about
$17,849.

However, the model can potentially be improved by trying
different algorithms and better feature engineering.


──────────────────────────────────────────────────────────────
7. QUICK RULE TO REMEMBER
──────────────────────────────────────────────────────────────

MAE  → Average prediction error
MSE  → Squared prediction error
RMSE → Error measure in the original price unit
R²   → How much variation the model explains

For MAE, MSE and RMSE:
LOWER = BETTER

For R²:
HIGHER = GENERALLY BETTER


──────────────────────────────────────────────────────────────
8. OUR CURRENT ML WORKFLOW
──────────────────────────────────────────────────────────────

Load data
    ↓
Understand features
    ↓
Clean data
    ↓
Separate X and y
    ↓
Split into training and testing data
    ↓
Handle missing values
    ↓
Encode categorical variables
    ↓
Train Linear Regression
    ↓
Make predictions
    ↓
Evaluate MAE, MSE, RMSE and R²
    ↓
Improve the model
    ↓
Try other algorithms
    ↓
Compare models

Your key result to remember: R² = 0.8849, meaning your current Linear Regression model explains about 88.5% of the variation in house prices on the test set.

SyntaxError: invalid character '╔' (U+2554) (497478361.py, line 3)

In [193]:
#LET'S BUILD ANOTHER MACHINE LEARNING MODEL#

In [194]:
#Linear Regression is our baseline model. Now we'll build the second model: Decision Tree Regressor#.

In [195]:
#-Import the Decision Tree model - Create a new cell below your Linear Regression evaluation and run-#

In [196]:
from sklearn.tree import DecisionTreeRegressor

In [197]:
#Create the Decision Tree model#

In [198]:
tree_model = DecisionTreeRegressor(
    random_state=42
)

In [199]:
#Train the model#

In [200]:
tree_model.fit(X_train, y_train)

ValueError: could not convert string to float: 'RL'

In [ ]:
#CREATE A NEW PIPELINE#

In [201]:
from sklearn.pipeline import Pipeline

tree_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", DecisionTreeRegressor(random_state=42))
])

In [202]:
#NOW TRAIN AGAIN#

In [203]:
tree_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('to_string',
                                                                   FunctionTransformer(func=<function <lambda> at 0x000001FBC7C15800>)),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['MS Zoning', 'Street',
                                                   'Alley', 'Lot Shape',
                                                   'Land Contour', 'Utilities',
                                                   'Lot C...
                                                   'BsmtFin SF 1',
                                                   'BsmtFin SF 2',
                                                   'Bsmt Unf SF',
                                                   'Total Bsmt SF',
                                                   '1st Flr SF', '2nd Flr SF',
                                                   'Low Qual Fin SF',
                                                   'Gr Liv Area',
                                                   'Bsmt Full Bath',
                                                   'Bsmt Half Bath',
                                                   'Full Bath', 'Half Bath',
                                                   'Bedroom AbvGr',
                                                   'Kitchen AbvGr',
                                                   'TotRms AbvGrd',
                                                   'Fireplaces', 'Garage Cars',
                                                   'Garage Area',
                                                   'Wood Deck SF',
                                                   'Open Porch SF',
                                                   'Enclosed Porch',
                                                   '3Ssn Porch', ...])])),
                ('model', DecisionTreeRegressor(random_state=42))])

In [204]:
#MAKE PREDICTIONS#

In [205]:
tree_pred = tree_pipeline.predict(X_test)

In [206]:
tree_pred[:10]

array([130000.,  88000., 207500., 118500., 120000., 164990., 130000.,
       144000.,  86900., 325624.])

In [207]:
#EVALUATE IT#

In [208]:
tree_mae = mean_absolute_error(y_test, tree_pred)
tree_mse = mean_squared_error(y_test, tree_pred)
tree_rmse = np.sqrt(tree_mse)
tree_r2 = r2_score(y_test, tree_pred)

print("Decision Tree Results")
print("------------------------")
print("MAE :", tree_mae)
print("MSE :", tree_mse)
print("RMSE:", tree_rmse)
print("R²  :", tree_r2)

Decision Tree Results
------------------------
MAE : 23486.494880546074
MSE : 1220294779.3686006
RMSE: 34932.71789266619
R²  : 0.847797008526217

In [209]:
#NOW LET'S TRY MODEL 3: RANDOM FOREST#

In [210]:
#Step 1 — Import Random Forest#

In [211]:
from sklearn.ensemble import RandomForestRegressor

In [212]:
#Step 2 — Create the model#

In [213]:
rf_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(
        n_estimators=200,
        random_state=42,
        n_jobs=-1
    ))
])

In [214]:
#Step 3 — Train it#

In [215]:
rf_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('to_string',
                                                                   FunctionTransformer(func=<function <lambda> at 0x000001FBC7C15800>)),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['MS Zoning', 'Street',
                                                   'Alley', 'Lot Shape',
                                                   'Land Contour', 'Utilities',
                                                   'Lot C...
                                                   'Bsmt Unf SF',
                                                   'Total Bsmt SF',
                                                   '1st Flr SF', '2nd Flr SF',
                                                   'Low Qual Fin SF',
                                                   'Gr Liv Area',
                                                   'Bsmt Full Bath',
                                                   'Bsmt Half Bath',
                                                   'Full Bath', 'Half Bath',
                                                   'Bedroom AbvGr',
                                                   'Kitchen AbvGr',
                                                   'TotRms AbvGrd',
                                                   'Fireplaces', 'Garage Cars',
                                                   'Garage Area',
                                                   'Wood Deck SF',
                                                   'Open Porch SF',
                                                   'Enclosed Porch',
                                                   '3Ssn Porch', ...])])),
                ('model',
                 RandomForestRegressor(n_estimators=200, n_jobs=-1,
                                       random_state=42))])

In [216]:
#Make predictions#

In [217]:
rf_pred = rf_pipeline.predict(X_test)

In [218]:
rf_pred[:10]

array([189057.84 , 102552.77 , 195147.905, 117330.16 , 112033.   ,
       176767.045, 164985.   , 149192.845,  90227.13 , 354952.92 ])

In [219]:
#EVALUATE#

In [220]:
rf_mae = mean_absolute_error(y_test, rf_pred)
rf_mse = mean_squared_error(y_test, rf_pred)
rf_rmse = np.sqrt(rf_mse)
rf_r2 = r2_score(y_test, rf_pred)

print("Random Forest Results")
print("------------------------")
print("MAE :", rf_mae)
print("MSE :", rf_mse)
print("RMSE:", rf_rmse)
print("R²  :", rf_r2)

Random Forest Results
------------------------
MAE : 15791.490981228668
MSE : 712167490.0051208
RMSE: 26686.466420362227
R²  : 0.9111739030259233

In [221]:
#Next: Model 4 — Gradient Boosting Regressor#

In [222]:
#Step 1 — Import it#

In [223]:
from sklearn.ensemble import GradientBoostingRegressor

In [224]:
#Step 2 — Create the pipeline#

In [225]:
gb_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", GradientBoostingRegressor(
        n_estimators=200,
        learning_rate=0.05,
        max_depth=3,
        random_state=42
    ))
])

In [226]:
#Step 3 — Train#

In [227]:
gb_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('to_string',
                                                                   FunctionTransformer(func=<function <lambda> at 0x000001FBC7C15800>)),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['MS Zoning', 'Street',
                                                   'Alley', 'Lot Shape',
                                                   'Land Contour', 'Utilities',
                                                   'Lot C...
                                                   'Total Bsmt SF',
                                                   '1st Flr SF', '2nd Flr SF',
                                                   'Low Qual Fin SF',
                                                   'Gr Liv Area',
                                                   'Bsmt Full Bath',
                                                   'Bsmt Half Bath',
                                                   'Full Bath', 'Half Bath',
                                                   'Bedroom AbvGr',
                                                   'Kitchen AbvGr',
                                                   'TotRms AbvGrd',
                                                   'Fireplaces', 'Garage Cars',
                                                   'Garage Area',
                                                   'Wood Deck SF',
                                                   'Open Porch SF',
                                                   'Enclosed Porch',
                                                   '3Ssn Porch', ...])])),
                ('model',
                 GradientBoostingRegressor(learning_rate=0.05, n_estimators=200,
                                           random_state=42))])

In [228]:
#Step 4 — Predict#

In [229]:
gb_pred = gb_pipeline.predict(X_test)

In [230]:
gb_pred[:10]

array([190828.80259673, 109199.97196452, 192572.22564495, 127422.05648824,
       121327.75773747, 179273.18796054, 185365.3978946 , 152942.02037372,
        89172.30487748, 384138.67736376])

In [231]:
#EVALUATE#

In [232]:
gb_mae = mean_absolute_error(y_test, gb_pred)
gb_mse = mean_squared_error(y_test, gb_pred)
gb_rmse = np.sqrt(gb_mse)
gb_r2 = r2_score(y_test, gb_pred)

print("Gradient Boosting Results")
print("------------------------")
print("MAE :", gb_mae)
print("MSE :", gb_mse)
print("RMSE:", gb_rmse)
print("R²  :", gb_r2)

Gradient Boosting Results
------------------------
MAE : 15140.015139877903
MSE : 666678155.7203151
RMSE: 25820.11145832479
R²  : 0.916847624552357

In [ ]:
#Confirm there are no missing values remaining#

In [237]:
df.isnull().sum().sum()

np.int64(0)

In [ ]:
#SAVE THE FINAL CLEANED_DATASET#

In [238]:
df.to_csv("AmesHousing_Cleaned.csv", index=False)

In [ ]:
#VERIFY WHERE IT WAS SAVED#

In [239]:
import os
os.getcwd()

'C:\\Users\\USER\\anaconda3'

In [ ]:
#TO BE SURE IT GOES TO ML_PROJECTS, RUN#

In [240]:
df.to_csv(r"C:\Users\USER\Desktop\ML_PROJECTS\AmesHousing_Cleaned.csv", index=False)

In [242]:
df.head(50)

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,None,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,5,1960,1960,Hip,CompShg,BrkFace,Plywood,Stone,112.0,TA,TA,CBlock,TA,Gd,Gd,BLQ,639.0,Unf,0.0,441.0,1080.0,GasA,Fa,Y,SBrkr,1656,0,0,1656,1.0,0.0,1,0,3,1,TA,7,Typ,2,Gd,Attchd,1960.0,Fin,2.0,528.0,TA,TA,P,210,62,0,0,0,0,None,None,None,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,Norm,1Fam,1Story,5,6,1961,1961,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,CBlock,TA,TA,No,Rec,468.0,LwQ,144.0,270.0,882.0,GasA,TA,Y,SBrkr,896,0,0,896,0.0,0.0,1,0,2,1,TA,5,Typ,0,None,Attchd,1961.0,Unf,1.0,730.0,TA,TA,Y,140,0,0,0,120,0,None,MnPrv,None,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,None,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,6,1958,1958,Hip,CompShg,Wd Sdng,Wd Sdng,BrkFace,108.0,TA,TA,CBlock,TA,TA,No,ALQ,923.0,Unf,0.0,406.0,1329.0,GasA,TA,Y,SBrkr,1329,0,0,1329,0.0,0.0,1,1,3,1,Gd,6,Typ,0,None,Attchd,1958.0,Unf,1.0,312.0,TA,TA,Y,393,36,0,0,0,0,None,None,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,None,Reg,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,7,5,1968,1968,Hip,CompShg,BrkFace,BrkFace,None,0.0,Gd,TA,CBlock,TA,TA,No,ALQ,1065.0,Unf,0.0,1045.0,2110.0,GasA,Ex,Y,SBrkr,2110,0,0,2110,1.0,0.0,2,1,3,1,Ex,8,Typ,2,TA,Attchd,1968.0,Fin,2.0,522.0,TA,TA,Y,0,0,0,0,0,0,None,None,None,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,5,5,1997,1998,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,PConc,Gd,TA,No,GLQ,791.0,Unf,0.0,137.0,928.0,GasA,Gd,Y,SBrkr,928,701,0,1629,0.0,0.0,2,1,3,1,TA,6,Typ,1,TA,Attchd,1997.0,Fin,2.0,482.0,TA,TA,Y,212,34,0,0,0,0,None,MnPrv,None,0,3,2010,WD,Normal,189900
5,6,527105030,60,RL,78.0,9978,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,6,1998,1998,Gable,CompShg,VinylSd,VinylSd,BrkFace,20.0,TA,TA,PConc,TA,TA,No,GLQ,602.0,Unf,0.0,324.0,926.0,GasA,Ex,Y,SBrkr,926,678,0,1604,0.0,0.0,2,1,3,1,Gd,7,Typ,1,Gd,Attchd,1998.0,Fin,2.0,470.0,TA,TA,Y,360,36,0,0,0,0,None,None,None,0,6,2010,WD,Normal,195500
6,7,527127150,120,RL,41.0,4920,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,StoneBr,Norm,Norm,TwnhsE,1Story,8,5,2001,2001,Gable,CompShg,CemntBd,CmentBd,None,0.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,616.0,Unf,0.0,722.0,1338.0,GasA,Ex,Y,SBrkr,1338,0,0,1338,1.0,0.0,2,0,2,1,Gd,6,Typ,0,None,Attchd,2001.0,Fin,2.0,582.0,TA,TA,Y,0,0,170,0,0,0,None,None,None,0,4,2010,WD,Normal,213500
7,8,527145080,120,RL,43.0,5005,Pave,None,IR1,HLS,AllPub,Inside,Gtl,StoneBr,Norm,Norm,TwnhsE,1Story,8,5,1992,1992,Gable,CompShg,HdBoard,HdBoard,None,0.0,Gd,TA,PConc,Gd,TA,No,ALQ,263.0,Unf,0.0,1017.0,1280.0,GasA,Ex,Y,SBrkr,1280,0,0,1280,0.0,0.0,2,0,2,1,Gd,5,Typ,0,None,Attchd,1992.0,RFn,2.0,506.0,TA,TA,Y,0,82,0,0,144,0,None,None,None,0,1,2010,WD,Normal,191500
8,9,527146030,120,RL,39.0,5389,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,StoneBr,Norm,Norm,TwnhsE,1Story,8,5,1995,1996,Gable,CompShg,CemntBd,CmentBd,None,0.0,Gd,TA,PConc,Gd,TA,No,GLQ,1180.0,Unf,0.0,415.0,1595.0,GasA,Ex,Y,SBrkr,1616,0,0,1616,1.0,0.0,2,0,2,1,Gd,5,Typ,1,TA,Attchd,1995.0,RFn,2.0,608.0,TA,TA,Y,237,152,0,0,0,0,None,None,None,0,3,2010,WD,Normal,236500
9,10,527162130,60,RL,60.0,7500,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,7,5,1999,1999,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,PConc,TA,TA,No,Unf,0.0,Unf,0.0,994.0,994.0,GasA,Gd,Y,SBrkr,1028,776,0,1804,0.0,0.0,2,1,3,1,Gd,7,Typ,1,TA,Attchd,1999.0,Fin,2.0,442.0,TA,TA,Y,140,60,0,0,0,0,None,None,None,0,6,2010,WD,Normal,189000
10,11,527163010,60,RL,75.0,10000,Pave,None,IR1,Lvl,AllPub,Corner,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,5,1993,1994,Gable,CompShg,HdBoard,HdBoard,None,0.0,TA,TA,PConc,Gd,TA,No,Unf,0.0,Unf,0.0,763.0,763.0,GasA,Gd,Y,SBrkr,763,892,0,1655,0.0,0.0,2,1,3,1,TA,7,Typ,1,TA,Attchd,1993.0,Fin,2.0,440.0,TA,TA,Y,157,84,0,0,0,0,None,None,None,0,4,2010,WD,Normal,175900
11,12,527165230,20,RL,68.0,7980,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,1Story,6,7,1992,2007,Gable,CompShg,HdBoard,HdBoard,None,0.0,TA,Gd,PConc,Gd,TA,No,ALQ,935.0,Unf,0.0,233.0,1168.0,GasA,Ex,Y,SBrkr,1187,0,0,1187,1.0,0.0,2,0,3,1,TA,6,Typ,0,None,Attchd,1992.0,Fin,2.0,420.0,TA,TA,Y,483,21,0,0,0,0,None,GdPrv,Shed,500,3,2010,WD,Normal,185000
12,13,527166040,60,RL,63.0,8402,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,5,1998,1998,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,PConc,Gd,TA,No,Unf,0.0,Unf,0.0,789.0,789.0,GasA,Gd,Y,SBrkr,789,676,0,1465,0.0,0.0,2,1,3,1,TA,7,Typ,1,Gd,Attchd,1998.0,Fin,2.0,393.0,TA,TA,Y,0,75,0,0,0,0,None,None,None,0,5,2010,WD,Normal,180400
13,14,527180040,20,RL,85.0,10176,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,1Story,7,5,1990,1990,Gable,CompShg,HdBoard,HdBoard,None,0.0,TA,TA,PConc,Gd,TA,Gd,GLQ,637.0,Unf,0.0,663.0,1300.0,GasA,Gd,Y,SBrkr,1341,0,0,1341,1.0,0.0,1,1,2,1,Gd,5,Typ,1,Po,Attchd,1990.0,Unf,2.0,506.0,TA,TA,Y,192,0,0,0,0,0,None,None,None,0,2,2010,WD,Normal,171500
14,15,527182190,120,RL,68.0,6820,Pave,None,IR1,Lvl,AllPub,Corner,Gtl,StoneBr,Norm,Norm,TwnhsE,1Story,8,5,1985,1985,Gable,CompShg,HdBoard,HdBoard,None,0.0,Gd,TA,PConc,Gd,TA,Av,GLQ,368.0,BLQ,1120.0,0.0,1488.0,GasA,TA,Y,SBrkr,1502,0,0,1502,1.0,0.0,1,1,1,1,Gd,4,Typ,0,None,Attchd,1985.0,RFn,2.0,528.0,TA,TA,Y,0,54,0,0,140,0,None,None,None,0,6,2010,WD,Normal,212000
15,16,527216070,60,RL,47.0,53504,Pave,None,IR2,HLS,AllPub,CulDSac,Mod,StoneBr,Norm,Norm,1Fam,2Story,8,5,2003,2003,Hip,CompShg,CemntBd,Wd Shng,BrkFace,603.0,Ex,TA,PConc,Gd,TA,Gd,ALQ,1416.0,Unf,0.0,234.0,1650.0,GasA,Ex,Y,SBrkr,1690,1589,0,3279,1.0,0.0,3,1,4,1,Ex,12,Mod,1,Gd,BuiltIn,2003.0,Fin,3.0,841.0,TA,TA,Y,503,36,0,0,210,0,None,None,None,0,6,2010,WD,Normal,538000
16,17,527225035,50,RL,152.0,12134,Pave,None,IR1,Bnk,AllPub,Inside,Mod,Gilbert,Norm,Norm,1Fam,1.5Fin,8,7,1988,2005,Gable,CompShg,Wd Sdng,Wd Sdng,None,0.0,Gd,TA,Wood,Gd,TA,Av,GLQ,427.0,Unf,0.0,132.0,559.0,GasA,Gd,Y,SBrkr,1080,672,0,1752,0.0,0.0,2,0,4,1,TA,8,Typ,0,None,Basment,1988.0,RFn,2.0,492.0,TA,TA,Y,325,12,0,0,0,0,None,None,None,0,6,2010,WD,Normal,164000
17,18,527258010,20,RL,88.0,11394,Pave,None,Reg,Lvl,AllPub,Corner,Gtl,StoneBr,Norm,Norm,1Fam,1Story,9,2,2010,2010,Hip,CompShg,VinylSd,VinylSd,Stone,350.0,Gd,TA,PConc,Ex,TA,Av,GLQ,1445.0,Unf,0.0,411.0,1856.0,GasA,Ex,Y,SBrkr,1856,0,0,1856,1.0,0.0,1,1,1,1,Ex,8,Typ,1,Ex,Attchd,2010.0,Fin,3.0,834.0,TA,TA,Y,113,0,0,0,0,0,None,None,None,0,6,2010,New,Partial,394432
18,19,527276150,20,RL,140.0,19138,Pave,None,Reg,Lvl,AllPub,Corner,Gtl,Gilbert,Norm,Norm,1Fam,1Story,4,5,1951,1951,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,CBlock,TA,TA,No,LwQ,120.0,Unf,0.0,744.0,864.0,GasA,Ex,Y,SBrkr,864,0,0,864,0.0,0.0,1,0,2,1,TA,4,Typ,0,None,Detchd,1951.0,Unf,2.0,400.0,TA,TA,Y,0,0,0,0,0,0,None,None,None,0,6,2010,WD,Normal,141000
19,20,527302110,20,RL,85.0,13175,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,6,6,1978,1988,Gable,CompShg,Plywood,Plywood,Stone,119.0,TA,TA,CBlock,Gd,TA,No,ALQ,790.0,Rec,163.0,589.0,1542.0,GasA,TA,Y,SBrkr,2073,0,0,2073,1.0,0.0,2,0,3,1,TA,7,Min1,2,TA,Attchd,1978.0,Unf,2.0,500.0,TA,TA,Y,349,0,0,0,0,0,None,MnPrv,None,0,2,2010,WD,Normal,210000
20,21,527358140,20,RL,105.0,11751,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,6,6,1977,1977,Hip,CompShg,Plywood,Plywood,BrkFace,480.0,TA,TA,CBlock,Gd,TA,No,BLQ,705.0,Unf,0.0,1139.0,1844.0,GasA,Ex,Y,SBrkr,1844,0,0,1844,0.0,0.0,2,0,3,1,TA,7,Typ,1,TA,Attchd,1977.0,RFn,2.0,546.0,TA,TA,Y,0,122,0,0,0,0,None,MnPrv,None,0,1,2010,COD,Normal,190000
21,22,527358200,85,RL,85.0,10625,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,SFoyer,7,6,1974,1974,Gable,CompShg,Plywood,Plywood,BrkFace,81.0,TA,TA,CBlock,Gd,TA,Gd,GLQ,885.0,LwQ,168.0,0.0,1053.0,GasA,TA,Y,SBrkr,1173,0,0,1173,1.0,0.0,2,0,3,1,Gd,6,Typ,2,TA,Attchd,1974.0,RFn,2.0,528.0,TA,TA,Y,0,120,0,0,0,0,None,MnPrv,None,0,1,2010,WD,Family,170000
22,23,527368020,60,FV,68.0,7500,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,Somerst,Norm,Norm,1Fam,2Story,7,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,None,0.0,Gd,TA,PConc,Gd,TA,No,GLQ,533.0,Unf,0.0,281.0,814.0,GasA,Ex,Y,SBrkr,814,860,0,1674,1.0,0.0,2,1,3,1,Gd,7,Typ,0,None,Attchd,2000.0,RFn,2.0,663.0,TA,TA,Y,0,96,0,0,0,0,None,None,None,0,1,2010,WD,Normal,216000
23,24,527402200,20,RL,68.0,11241,Pave,None,IR1,Lvl,AllPub,CulDSac,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,7,1970,1970,Gable,CompShg,Wd Sdng,Wd Sdng,BrkFace,180.0,TA,TA,CBlock,TA,TA,No,ALQ,578.0,Unf,0.0,426.0,1004.0,GasA,Ex,Y,SBrkr,1004,0,0,1004,1.0,0.0,1,0,2,1,TA,5,Typ,1,TA,Attchd,1970.0,Fin,2.0,480.0,TA,TA,Y,0,0,0,0,0,0,None,None,Shed,700,3,2010,WD,Normal,149000
24,25,527402250,20,RL,68.0,12537,Pave,None,IR1,Lvl,AllPub,CulDSac,Gtl,NAmes,Norm,Norm,1Fam,1Story,5,6,1971,2008,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,CBlock,TA,TA,No,GLQ,734.0,Unf,0.0,344.0,1078.0,GasA,Ex,Y,SBrkr,1078,0,0,1078,1.0,0.0,1,1,3,1,TA,6,Typ,1,Fa,Attchd,1971.0,Fin,2.0,500.0,TA,TA,Y,0,0,0,0,0,0,None,None,None,0,4,2010,WD,Normal,149900
25,26,527403020,20,RL,65.0,8450,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,5,6,1968,1968,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,CBlock,TA,TA,No,BLQ,775.0,Unf,0.0,281.0,1056.0,GasA,Ex,Y,SBrkr,1056,0,0,1056,1.0,0.0,1,0,3,1,TA,6,Typ,1,Fa,Attchd,1968.0,Unf,1.0,304.0,TA,TA,Y,0,85,184,0,0,0,None,None,None,0,7,2010,WD,Normal,142000
26,27,527404120,20,RL,70.0,8400,Pave,None,Reg,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,4,5,1970,1970,Gable,CompShg,Plywood,Plywood,None,0.0,TA,TA,CBlock,TA,TA,No,ALQ,804.0,Rec,78.0,0.0,882.0,GasA,TA,Y,SBrkr,882,0,0,882,1.0,0.0,1,0,2,1,TA,4,Typ,0,None,Attchd,1970.0,Fin,2.0,525.0,TA,TA,Y,240,0,0,0,0,0,None,MnPrv,None,0,4,2010,WD,Normal,126000
27,28,527425090,20,RL,70.0,10500,Pave,None,Reg,Lvl,AllPub,FR2,Gtl,NAmes,Norm,Norm,1Fam,1Story,4,5,1971,1971,Gable,CompShg,HdBoard,HdBoard,None,0.0,TA,TA,CBlock,TA,TA,No,ALQ,432.0,Unf,0.0,432.0,864.0,GasA,TA,Y,SBrkr,864,0,0,864,0.0,0.0,1,0,3,1,TA,5,Typ,1,Po,None,None,None,0.0,0.0,None,None,Y,0,0,0,0,0,0,None,None,None,0,4,2010,ConLI,Normal,115000
28,29,527427230,120,RH,26.0,5858,Pave,None,IR1,Lvl,AllPub,FR2,Gtl,NAmes,Norm,Norm,TwnhsE,1Story,7,5,1999,1999,Gable,CompShg,MetalSd,MetalSd,None,0.0,Gd,TA,PConc,Gd,TA,No,GLQ,1051.0,BLQ,0.0,354.0,1405.0,GasA,Ex,Y,SBrkr,1337,0,0,1337,1.0,0.0,2,0,2,1,Gd,5,Typ,1,Fa,Attchd,1999.0,Fin,2.0,511.0,TA,TA,Y,203,68,0,0,0,0,None,None,None,0,6,2010,WD,Normal,184000
29,30,527451180,160,RM,21.0,1680,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,BrDale,Norm,Norm,Twnhs,2Story,6,5,1971,1971,Gable,CompShg,HdBoard,HdBoard,BrkFace,504.0,TA,TA,CBlock,TA,TA,No,Rec,156.0,Unf,0.0,327.0,483.0,GasA,TA,Y,SBrkr,483,504,0,987,0.0,0.0,1,1,2,1,TA,5,Typ,0,None,Detchd,1971.0,Unf,1.0,264.0,TA,TA,Y,275,0,0,0,0,0,None,None,None,0,2,2010,COD,Normal,96000
30,31,527451330,160,RM,21.0,1680,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,BrDale,Norm,Norm,Twnhs,2Story,5,5,1971,1971,Gable,CompShg,HdBoard,HdBoard,BrkFace,492.0,TA,TA,CBlock,TA,TA,No,Rec,300.0,Unf,0.0,225.0,525.0,GasA,TA,Y,SBrkr,525,567,0,1092,0.0,0.0,1,1,3,1,TA,6,Typ,0,None,Detchd,1997.0,Unf,1.0,320.0,TA,TA,Y,0,0,0,0,0,0,None,None,None,0,3,2010,WD,Normal,105500
31,32,527451410,160,RM,21.0,1680,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,BrDale,Norm,Norm,Twnhs,2Story,6,5,1971,1971,Gable,CompShg,HdBoard,ImStucc,BrkFace,381.0,TA,TA,CBlock,TA,TA,No,Unf,0.0,Unf,0.0,525.0,525.0,GasA,TA,Y,SBrkr,525,567,0,1092,0.0,0.0,1,1,3,1,TA,6,Typ,0,None,Detchd,1971.0,Unf,1.0,264.0,TA,TA,Y,0,0,0,0,0,0,None,None,None,0,3,2010,WD,Family,88000
32,33,527452190,120,RL,53.0,4043,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,NPkVill,Norm,Norm,TwnhsE,1Story,6,5,1977,1977,Gable,CompShg,Plywood,Plywood,None,0.0,TA,TA,CBlock,Gd,TA,No,ALQ,360.0,Unf,0.0,709.0,1069.0,GasA,TA,Y,SBrkr,1069,0,0,1069,0.0,0.0,2,0,2,1,TA,4,Typ,1,Fa,Attchd,1977.0,RFn,2.0,440.0,TA,TA,Y,0,55,0,0,165,0,None,None,None,0,7,2010,WD,Normal,127500
33,34,527453130,160,RL,24.0,2280,Pave,None,Reg,Lvl,AllPub,FR2,Gtl,NPkVill,Norm,Norm,Twnhs,2Story,6,6,1975,1975,Gable,CompShg,Plywood,Brk Cmn,None,0.0,TA,TA,CBlock,TA,TA,No,ALQ,514.0,Unf,0.0,341.0,855.0,GasA,TA,Y,SBrkr,855,601,0,1456,0.0,0.0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,1975.0,Unf,2.0,440.0,TA,TA,Y,173,0,0,0,0,0,None,None,None,0,6,2010,WD,Normal,149900
34,35,527453150,120,RL,24.0,2280,Pave,None,Reg,Lvl,AllPub,FR2,Gtl,NPkVill,Norm,Norm,Twnhs,1Story,7,6,1975,1975,Gable,CompShg,Plywood,Brk Cmn,None,0.0,TA,TA,CBlock,Gd,TA,No,Unf,0.0,Unf,0.0,836.0,836.0,GasA,Ex,Y,SBrkr,836,0,0,836,0.0,0.0,1,0,2,1,TA,4,Typ,0,None,Attchd,1975.0,Unf,1.0,308.0,TA,TA,Y,0,30,0,0,0,0,None,None,None,0,6,2010,WD,Normal,120000
35,36,527454200,160,RL,24.0,2280,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,NPkVill,Norm,Norm,Twnhs,2Story,6,5,1978,1978,Gable,CompShg,Plywood,Brk Cmn,None,0.0,TA,TA,CBlock,Gd,TA,No,ALQ,311.0,Unf,0.0,544.0,855.0,GasA,Fa,Y,SBrkr,855,601,0,1456,0.0,0.0,2,1,3,1,TA,7,Typ,1,TA,Attchd,1978.0,Unf,2.0,440.0,TA,TA,Y,26,0,0,0,0,0,None,None,None,0,7,2010,WD,Normal,146000
36,37,528108120,60,RL,102.0,12858,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,NridgHt,Norm,Norm,1Fam,2Story,9,5,2009,2010,Gable,CompShg,VinylSd,VinylSd,Stone,162.0,Ex,TA,PConc,Ex,TA,No,Unf,0.0,Unf,0.0,1590.0,1590.0,GasA,Ex,Y,SBrkr,1627,707,0,2334,0.0,0.0,2,1,3,1,Ex,10,Typ,1,Gd,Attchd,2009.0,Fin,3.0,751.0,TA,TA,Y,144,133,0,0,0,0,None,None,None,0,1,2010,New,Partial,376162
37,38,528112020,20,RL,98.0,11478,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,NridgHt,Norm,Norm,1Fam,1Story,8,5,2007,2008,Gable,CompShg,VinylSd,VinylSd,Stone,200.0,Gd,TA,PConc,Ex,TA,No,GLQ,1218.0,Unf,0.0,486.0,1704.0,GasA,Ex,Y,SBrkr,1704,0,0,1704,1.0,0.0,2,0,3,1,Gd,7,Typ,1,Gd,Attchd,2008.0,RFn,3.0,772.0,TA,TA,Y,0,50,0,0,0,0,None,None,None,0,5,2010,WD,Normal,306000
38,39,528120060,20,RL,83.0,10159,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,NridgHt,Norm,Norm,1Fam,1Story,9,5,2009,2010,Hip,CompShg,VinylSd,VinylSd,Stone,450.0,Ex,TA,PConc,Ex,TA,Av,GLQ,1646.0,Unf,0.0,284.0,1930.0,GasA,Ex,Y,SBrkr,1940,0,0,1940,1.0,0.0,2,1,3,1,Ex,8,Typ,1,Gd,Attchd,2010.0,Fin,3.0,606.0,TA,TA,Y,168,95,0,0,0,0,None,None,None,0,4,2010,New,Partial,395192
39,40,528120090,20,RL,94.0,12883,Pave,None,IR1,Lvl,AllPub,Corner,Gtl,NridgHt,Norm,Norm,1Fam,1Story,8,5,2009,2010,Gable,CompShg,VinylSd,VinylSd,Stone,256.0,Gd,TA,PConc,Gd,TA,No,Unf,0.0,Unf,0.0,1544.0,1544.0,GasA,Ex,Y,SBrkr,1544,0,0,1544,0.0,0.0,2,0,3,1,Gd,7,Typ,0,None,Attchd,2009.0,RFn,3.0,868.0,TA,TA,Y,0,35,0,0,0,0,None,None,None,0,6,2010,New,Partial,290941
40,41,528120100,20,RL,95.0,12182,Pave,None,Reg,Lvl,AllPub,Corner,Gtl,NridgHt,Norm,Norm,1Fam,1Story,7,5,2005,2005,Gable,CompShg,VinylSd,VinylSd,BrkFace,226.0,Gd,TA,PConc,Gd,TA,Mn,BLQ,1201.0,Unf,0.0,340.0,1541.0,GasA,Ex,Y,SBrkr,1541,0,0,1541,0.0,0.0,2,0,3,1,Gd,7,Typ,1,Gd,Attchd,2005.0,RFn,2.0,532.0,TA,TA,Y,0,70,0,0,0,0,None,None,None,0,5,2010,New,Partial,220000
41,42,528120120,20,RL,90.0,11520,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,NridgHt,PosN,Norm,1Fam,1Story,9,5,2005,2005,Hip,CompShg,VinylSd,VinylSd,BrkFace,615.0,Gd,TA,PConc,Ex,TA,No,GLQ,110.0,Unf,0.0,1588.0,1698.0,GasA,Ex,Y,SBrkr,1698,0,0,1698,0.0,0.0,2,0,3,1,Ex,7,Typ,1,Gd,Attchd,2005.0,Fin,3.0,730.0,TA,TA,Y,192,74,0,0,0,0,None,None,None,0,6,2010,WD,Normal,275000
42,43,528138020,20,RL,79.0,14122,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,NridgHt,Norm,Norm,1Fam,1Story,8,5,2005,2006,Hip,CompShg,CemntBd,CmentBd,BrkFace,240.0,Gd,TA,PConc,Ex,TA,No,GLQ,28.0,Unf,0.0,1794.0,1822.0,GasA,Ex,Y,SBrkr,1822,0,0,1822,0.0,0.0,2,0,3,1,Ex,8,Typ,1,Gd,Attchd,2005.0,RFn,3.0,678.0,TA,TA,Y,0,119,0,0,0,0,None,None,None,0,2,2010,WD,Normal,259000
43,44,528138060,20,RL,70.0,10171,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,NridgHt,Norm,Norm,1Fam,1Story,7,5,2004,2004,Gable,CompShg,VinylSd,VinylSd,BrkFace,168.0,Gd,TA,PConc,Gd,TA,No,GLQ,2.0,Unf,0.0,1515.0,1517.0,GasA,Ex,Y,SBrkr,1535,0,0,1535,0.0,0.0,2,0,3,1,Gd,7,Typ,0,None,Attchd,2004.0,RFn,2.0,532.0,TA,TA,Y,0,0,0,0,0,0,None,None,None,0,3,2010,WD,Normal,214000
44,45,528150070,20,RL,100.0,12919,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,NridgHt,Norm,Norm,1Fam,1Story,9,5,2009,2010,Hip,CompShg,VinylSd,VinylSd,Stone,760.0,Ex,TA,PConc,Ex,TA,Gd,GLQ,2188.0,Unf,0.0,142.0,2330.0,GasA,Ex,Y,SBrkr,2364,0,0,2364,1.0,0.0,2,1,2,1,Ex,11,Typ,2,Gd,Attchd,2009.0,Fin,3.0,820.0,TA,TA,Y,0,67,0,0,0,0,None,None,None,0,3,2010,New,Partial,611657
45,46,528175010,120,RL,44.0,6371,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,NridgHt,Norm,Norm,TwnhsE,1Story,7,5,2009,2010,Gable,CompShg,VinylSd,VinylSd,Stone,128.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,733.0,Unf,0.0,625.0,1358.0,GasA,Ex,Y,SBrkr,1358,0,0,1358,1.0,0.0,2,0,2,1,Gd,6,Typ,1,Gd,Attchd,2010.0,RFn,2.0,484.0,TA,TA,Y,192,35,0,0,0,0,None,None,None,0,6,2010,New,Partial,224000
46,47,528176010,20,RL,110.0,14300,Pave,None,Reg,HLS,AllPub,Inside,Mod,NridgHt,Norm,Norm,1Fam,1Story,9,5,2003,2004,Hip,CompShg,VinylSd,VinylSd,BrkFace,1095.0,Ex,TA,PConc,Ex,TA,Gd,GLQ,1373.0,Unf,0.0,1473.0,2846.0,GasA,Ex,Y,SBrkr,2696,0,0,2696,1.0,0.0,2,1,3,1,Ex,10,Typ,2,Gd,Attchd,2003.0,Fin,3.0,958.0,TA,TA,Y,220,150,0,0,0,0,None,None,None,0,6,2010,WD,Normal,500000
47,48,528176070,60,RL,105.0,13650,Pave,None,Reg,Lvl,AllPub,Corner,Gtl,NridgHt,Norm,Norm,1Fam,2Story,8,5,2002,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,232.0,Gd,TA,PConc,Gd,TA,Gd,GLQ,578.0,Unf,0.0,1093.0,1671.0,GasA,Ex,Y,SBrkr,1687,563,0,2250,1.0,0.0,2,1,3,1,Gd,7,Typ,1,Ex,Attchd,2002.0,Fin,3.0,756.0,TA,TA,Y,238,130,0,0,0,0,None,None,None,0,6,2010,WD,Normal,320000
48,49,528180070,120,RL,61.0,7658,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,NridgHt,Norm,Norm,TwnhsE,1Story,9,5,2005,2005,Hip,CompShg,MetalSd,MetalSd,BrkFace,412.0,Ex,TA,PConc,Ex,TA,No,GLQ,456.0,Unf,0.0,1296.0,1752.0,GasA,Ex,Y,SBrkr,1752,0,0,1752,1.0,0.0,2,0,2,1,Ex,6,Typ,1,Gd,Attchd,2005.0,RFn,2.0,576.0,TA,TA,Y,196,82,0,0,0,0,None,None,None,0,2,2010,WD,Normal,319900
49,50,528181050,120,RL,41.0,7132,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,NridgHt,Norm,Norm,TwnhsE,1Story,8,5,2006,2006,Gable,CompShg,VinylSd,VinylSd,Stone,178.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,24.0,Unf,0.0,1346.0,1370.0,GasA,Ex,Y,SBrkr,1370,0,0,1370,0.0,0.0,2,0,2,1,Gd,6,Typ,1,Gd,Attchd,2006.0,RFn,2.0,484.0,TA,TA,Y,120,49,0,0,0,0,None,None,None,0,4,2010,WD,Normal,205000